using CxCompiler.Model;
using CxCompiler.Model.Common;
using CxCompiler.Model.Expressions;
using CxCompiler.Model.Project;
using CxCompiler.Model.Types;
using CxCompiler.Model.Types.BuiltInTypes;
using System.Security.Cryptography;
using System.Text;

namespace CxCompiler.OutputGenerators;

public static partial class CCodeOutputGenerator
{
    public static void GenerateOutput(CxProject project, string filePath)
    {
        if (project == null)
        {
            throw new InternalCompilerException("Project is null");
        }

        WriteProjectHeaderFile(project, Path.Combine(Path.GetDirectoryName(filePath)!, $"{project.Name}.h"));
        WriteProjectSourceFile(project, Path.Combine(Path.GetDirectoryName(filePath)!, $"{project.Name}.c"));
    }

    private static void WriteProjectHeaderFile(CxProject project, string outputFilePath)
    {
        using var fileWriter = new StreamWriter(outputFilePath);
        var writer = new IndentingWriter(fileWriter);

        writer.WriteLine($"// This is an autogenerated C header file for project '{project.Name}'");
        writer.WriteLine();

        string headerGuardName = project.Name.ToUpperInvariant().Replace('.', '_');
        writer.WriteLine($"#ifndef _{headerGuardName}_H_");
        writer.WriteLine($"#define _{headerGuardName}_H_");
        writer.WriteLine();
        writer.WriteLine(project.Name == "cxcore"
            ? "#include <cx.h>"
            : "#include <cxcore.h>");
        writer.WriteLine();

        var declarations = GetDeclarations(project);

        writer.WriteLine("//");
        writer.WriteLine("// Forward type declarations");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteTypesForwardDeclarations(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Type declarations");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteTypesDeclarations(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Function and property declarations");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteFunctionsForwardDeclarations(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine();
        writer.WriteLine($"#endif // _{headerGuardName}_H_");

        fileWriter.Flush();
        fileWriter.Close();
    }

    private static void WriteTypesForwardDeclarations(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var declaration in declarations)
        {
            if (declaration is EnumDeclaration enumDeclaration)
            {
                var enumName = enumDeclaration.ToCIdentifier(moduleName);
                writer.WriteLine($"typedef enum {enumName} {{");
                writer.IncreaseIndent();
                for (var index = 0; index < enumDeclaration.Members.Count; index++)
                {
                    var member = enumDeclaration.Members[index];
                    var value = member.Value is null
                        ? string.Empty
                        : $" = {member.Value.SourceText}";
                    var comma = index + 1 < enumDeclaration.Members.Count ? "," : string.Empty;
                    writer.WriteLine($"{member.ToCIdentifier(moduleName)}{value}{comma}");
                }
                writer.DecreaseIndent();
                writer.WriteLine($"}} {enumName};");
            }
            else if (declaration is ClassDeclaration classDeclaration)
            {
                writer.WriteLine($"{classDeclaration.ToCIdentifier(moduleName)};");

                var memberDeclarations = classDeclaration.MemberDeclarations.Declarations
                    .Where(x => x is ClassDeclaration)
                    .ToArray();
                if (memberDeclarations.Length != 0)
                {
                    WriteTypesForwardDeclarations(writer, memberDeclarations, moduleName);
                }
            }
        }
    }

    private static void WriteTypesDeclarations(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var declaration in declarations)
        {
            if (declaration is ClassDeclaration classDeclaration)
            {
                if (classDeclaration.ClassType == ClassType.Class && classDeclaration.IsStatic)
                {
                    writer.WriteLine($"CX_STATIC_TYPE_DEF({classDeclaration.ToCIdentifier(moduleName, false)});");
                }
                else
                {
                    writer.WriteLine($"CX_TYPE_DEF({classDeclaration.ToCIdentifier(moduleName, false)}) {{");

                    writer.IncreaseIndent();

                    if (moduleName == "cxcore" && classDeclaration.Name == "Object")
                    {
                        writer.WriteLine("void* __vtable;");
                    }
                    else if (classDeclaration.ClassType == ClassType.Interface)
                    {
                        writer.WriteLine("void* __vtable;");
                        writer.WriteLine("void* __root;");
                    }
                    else if (classDeclaration.ClassType == ClassType.Class)
                    {
                        var baseType = classDeclaration.BaseClassType ?? BuiltInSystemTypes.Object;
                        writer.WriteLine($"{ToCStorageType(baseType)} __base;");
                    }

                    var fieldMemberDeclarations = classDeclaration.MemberDeclarations.Declarations
                        .OfType<FieldDeclaration>()
                        .Where(field => !field.IsStatic)
                        .ToArray();
                    if (!fieldMemberDeclarations.Any() &&
                        classDeclaration.ClassType == ClassType.Struct)
                    {
                        writer.WriteLine("cx_byte __dummy;");
                    }
                    else
                    {
                        foreach (var fieldDeclaration in fieldMemberDeclarations)
                        {
                            writer.WriteLine($"{fieldDeclaration.Type.ToCIdentifier(false)} {fieldDeclaration.Name};");
                            //if (fieldDeclaration.InitialValue != null)
                            //{
                            //    writer.Write($" = {fieldDeclaration.InitialValue.ToCIdentifier()}");
                            //}
                        }
                    }

                    writer.DecreaseIndent();
                    writer.WriteLine("};");

                }

                foreach (var staticField in classDeclaration.MemberDeclarations.Declarations
                    .OfType<FieldDeclaration>()
                    .Where(field => field.IsStatic))
                {
                    writer.WriteLine(
                        $"extern {staticField.Type.ToCIdentifier(false)} " +
                        $"{GetStaticFieldIdentifier(staticField, moduleName)};");
                }

                var classMemberDeclarations = classDeclaration.MemberDeclarations.Declarations
                    .OfType<ClassDeclaration>()
                    .ToArray();
                if (classMemberDeclarations.Length != 0)
                {
                    WriteTypesDeclarations(writer, classMemberDeclarations, moduleName);
                }
            }
        }
    }

    private static void WriteFunctionsForwardDeclarations(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        bool exportable;
        bool isFirstParameter;

        foreach (var declaration in declarations)
        {
            switch (declaration)
            {
                case ClassDeclaration classDeclaration:
                    var memberDeclarations = classDeclaration.MemberDeclarations.Declarations.ToArray();
                    if (memberDeclarations.Length != 0)
                    {
                        WriteFunctionsForwardDeclarations(writer, memberDeclarations, moduleName);
                    }

                    break;

                case FunctionDeclaration functionDeclaration:
                    if (functionDeclaration.ParentClassDeclaration?.ClassType == ClassType.Interface)
                    {
                        break;
                    }
                    exportable =
                        (
                            functionDeclaration.ParentClassDeclaration == null &&
                            functionDeclaration.MemberModifiers.Contains(MemberModifier.Public)
                        ) ||
                        (
                            functionDeclaration.ParentClassDeclaration?.ClassType == ClassType.Struct &&
                            functionDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            functionDeclaration.ParentClassDeclaration?.Visibility == Visibility.Public
                        ) ||
                        (
                            functionDeclaration.ParentClassDeclaration?.ClassType == ClassType.Class &&
                            functionDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            functionDeclaration.ParentClassDeclaration?.Visibility == Visibility.Public
                        ); // TODO: Traverse up all class hierarchy
                    var nameOverrideIndex = GetNameOverrideIndex(functionDeclaration, declarations);

                    writer.WriteIndent();
                    writer.Write($"extern {(exportable ? "CX_EXPORT " : "")}{functionDeclaration.ToCIdentifier(moduleName, nameOverrideIndex)}(");
                    writer.IncreaseIndent();

                    isFirstParameter = true;
                    if (!functionDeclaration.IsStatic)
                    {
                        writer.WriteNewLine();
                        writer.WriteIndent();
                        var receiverConst = functionDeclaration.Const ? "const " : string.Empty;
                        writer.Write($"{receiverConst}{functionDeclaration.ParentClassDeclaration!.ToCIdentifier(moduleName)}* __this");
                        isFirstParameter = false;
                    }

                    if (functionDeclaration.Parameters.Count > 0)
                    {
                        if (!isFirstParameter)
                        {
                            writer.Write(",");
                        }

                        writer.WriteNewLine();

                        for (int i = 0; i < functionDeclaration.Parameters.Count; i++)
                        {
                            FunctionParameter? parameter = functionDeclaration.Parameters[i];

                            //if (parameter.Name == "T")
                            //{
                            //    ;
                            //}

                            writer.WriteIndent();
                            writer.Write($"{parameter.ParameterType.ToCIdentifier(false /* TODO */)} {parameter.Name}");

                            //if (parameter.DefaultValue != null)
                            //{
                            //    writer.Write($" = {parameter.DefaultValue.ToCIdentifier()}");
                            //}

                            if (i != functionDeclaration.Parameters.Count - 1)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();
                        }
                    }
                    else if (!isFirstParameter)
                    {
                        writer.WriteLine();
                    }

                    writer.DecreaseIndent();
                    writer.WriteLine(");");
                    break;

                case PropertyDeclaration propertyDeclaration:
                    if (propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Interface)
                    {
                        break;
                    }
                    foreach (var propertyAccessorDeclaration in propertyDeclaration.PropertyAccessorDeclarations)
                    {
                        // TODO: Allow accessor declarations have member modifiers
                        exportable =
                        (
                            propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Interface
                        ) ||
                        (
                            propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Struct &&
                            propertyDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            propertyDeclaration.ParentClassDeclaration.Visibility == Visibility.Public
                        ) ||
                        (
                            propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Class &&
                            propertyDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            propertyDeclaration.ParentClassDeclaration.Visibility == Visibility.Public
                        ); // TODO: Traverse up all class hierarchy

                        writer.WriteIndent();
                        writer.Write($"extern {(exportable ? "CX_EXPORT " : "")}{propertyAccessorDeclaration.ToCIdentifier(moduleName)}(");
                        writer.IncreaseIndent();

                        isFirstParameter = true;
                        if (!propertyDeclaration.IsStatic)
                        {
                            writer.WriteNewLine();
                            writer.WriteIndent();
                            var receiverConst = propertyAccessorDeclaration.Const ? "const " : string.Empty;
                            writer.Write($"{receiverConst}{propertyDeclaration.ParentClassDeclaration.ToCIdentifier(moduleName)}* __this");
                            isFirstParameter = false;
                        }

                        if (propertyAccessorDeclaration.Parameters.Count > 0)
                        {
                            if (!isFirstParameter)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();

                            for (int i = 0; i < propertyAccessorDeclaration.Parameters.Count; i++)
                            {
                                FunctionParameter? parameter = propertyAccessorDeclaration.Parameters[i];
                                isFirstParameter = false;

                                writer.WriteIndent();
                                writer.Write($"{parameter.ParameterType.ToCIdentifier(false /* TODO */)} {parameter.Name}");

                                if (i != propertyAccessorDeclaration.Parameters.Count - 1)
                                {
                                    writer.Write(",");
                                }

                                writer.WriteNewLine();
                            }
                        }

                        var hasGenericValue = IsGenericValueType(propertyDeclaration.Type);
                        if (propertyAccessorDeclaration.Name == "set")
                        {
                            if (!isFirstParameter)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();
                            writer.WriteIndent();
                            writer.Write(hasGenericValue
                                ? "void* value"
                                : $"{propertyDeclaration.Type.ToCIdentifier(false)} value");
                            isFirstParameter = false;
                        }
                        else if (hasGenericValue)
                        {
                            if (!isFirstParameter)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();

                            writer.WriteIndent();
                            writer.Write("void* __returnValue");
                            isFirstParameter = false;
                        }

                        if (!isFirstParameter)
                        {
                            writer.WriteLine();
                        }

                        writer.DecreaseIndent();
                        writer.WriteLine(");");
                    }

                    break;
            }
        }
    }

    private static void WriteProjectSourceFile(CxProject project, string outputFilePath)
    {
        using var fileWriter = new StreamWriter(outputFilePath);
        var writer = new IndentingWriter(fileWriter);

        writer.WriteLine($"// This is an autogenerated C source file for project '{project.Name}'");
        writer.WriteLine();
        writer.WriteLine($"#include \"{project.Name}.h\"");
        writer.WriteLine();

        var declarations = GetDeclarations(project);

        writer.WriteLine("//");
        writer.WriteLine("// Strings");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteStrings(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Static fields");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteStaticFields(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Interface dispatch thunks");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteInterfaceDispatchThunks(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// TypeInfos");
        writer.WriteLine("//");
        WriteTypeInfos(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Functions");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteFunctionDefinitions(writer, declarations, project.Name);

        fileWriter.Flush();
        fileWriter.Close();
    }

    private static void WriteStrings(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        List<QualifiedIdentifier> namespaces = [];

        foreach (var declaration in declarations)
        {
            switch (declaration)
            {
                case ClassDeclaration classDeclaration:
                    var nameIdentifier = new QualifiedIdentifier("__name", classDeclaration.FullName);
                    writer.WriteLine($"CX_STRING_DEF({nameIdentifier.ToCIdentifier()}, \"{classDeclaration.Name}\");");

                    var @namespace = classDeclaration.Namespace;
                    if (!namespaces.Contains(@namespace))
                    {
                        namespaces.Add(@namespace);
                    }
                    break;
            }
        }

        foreach (var @namespace in namespaces)
        {
            var namespaceIdentifier = new QualifiedIdentifier("__namespace", @namespace);
            writer.WriteLine($"CX_STRING_DEF({namespaceIdentifier.ToCIdentifier()}, \"{@namespace}\");");
        }

        var functionLiterals = EnumerateFunctions(declarations)
            .Where(function => function.Body is not null)
            .SelectMany(function => function.Body!)
            .SelectMany(EnumerateStringLiterals);
        var fieldLiterals = EnumerateFields(declarations)
            .Where(field => field.Initializer is LiteralExpression { IsString: true })
            .Select(field => (LiteralExpression)field.Initializer!);
        foreach (var literal in functionLiterals
            .Concat(fieldLiterals)
            .DistinctBy(literal => literal.SourceText))
        {
            writer.WriteLine(
                $"CX_STRING_DEF({GetStringIdentifier(literal, moduleName).ToCIdentifier()}, {literal.SourceText});");
        }
    }

    private static void WriteStaticFields(
        IndentingWriter writer,
        IEnumerable<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var field in EnumerateFields(declarations).Where(field => field.IsStatic))
        {
            var initializer = field.Initializer is null
                ? string.Empty
                : $" = {ToCFieldInitializer(field.Initializer, moduleName)}";
            writer.WriteLine(
                $"{field.Type.ToCIdentifier(false)} {GetStaticFieldIdentifier(field, moduleName)}{initializer};");
        }
    }

    private static IEnumerable<FieldDeclaration> EnumerateFields(
        IEnumerable<DeclarationBase> declarations)
    {
        foreach (var declaration in declarations)
        {
            if (declaration is FieldDeclaration field)
            {
                yield return field;
            }
            else if (declaration is ClassDeclaration classDeclaration)
            {
                foreach (var nested in EnumerateFields(classDeclaration.MemberDeclarations.Declarations))
                {
                    yield return nested;
                }
            }
        }
    }

    private static string GetStaticFieldIdentifier(
        FieldDeclaration field,
        string moduleName)
    {
        return new QualifiedIdentifier(moduleName, field.FullName).ToCIdentifier();
    }

    private static string ToCFieldInitializer(ExpressionBase expression, string moduleName)
    {
        return expression switch
        {
            LiteralExpression { IsString: true } literal =>
                $"&{GetStringIdentifier(literal, moduleName).ToCIdentifier()}",
            LiteralExpression { SourceText: "true" } => "CX_TRUE",
            LiteralExpression { SourceText: "false" } => "CX_FALSE",
            LiteralExpression { SourceText: "null" } literal => ToCNullLiteral(literal),
            LiteralExpression literal => literal.SourceText,
            _ => throw new InternalCompilerException(
                $"Field initializer '{expression.GetType().Name}' is not supported."),
        };
    }

    private static QualifiedIdentifier GetStringIdentifier(
        LiteralExpression literal,
        string moduleName)
    {
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(literal.SourceText));
        return new QualifiedIdentifier(moduleName, $"__string_{Convert.ToHexString(hash.AsSpan(0, 8))}");
    }

    private static void WriteTypeInfos(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var declaration in declarations)
        {
            writer.WriteLine();

            switch (declaration)
            {
                case ClassDeclaration classDeclaration:
                    if (classDeclaration.ClassType == ClassType.Class && classDeclaration.IsStatic)
                    {
                        WriteTypeInfoDefinition(writer, classDeclaration, moduleName);
                    }
                    else
                    {
                        WriteVTableDefinition(writer, classDeclaration, moduleName);
                        WriteTypeInfoDefinition(writer, classDeclaration, moduleName);
                        foreach (var table in classDeclaration.InterfaceDispatchTables)
                        {
                            WriteInterfaceVTableDefinition(
                                writer,
                                classDeclaration,
                                table,
                                moduleName);
                        }
                    }
                    break;
            }
        }
    }

    private static void WriteTypeInfoDefinition(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        string moduleName)
    {
        var nameIdentifier = new QualifiedIdentifier("__name", classDeclaration.FullName);
        var namespaceIdentifier = new QualifiedIdentifier("__namespace", classDeclaration.Namespace);

        string[] flags = GetTypeInfoFlags(classDeclaration).ToArray();
        if (flags.Length == 0)
        {
            flags = ["0"];
        }
        string flagsString = string.Join(" | ", flags);

        if (classDeclaration.ClassType == ClassType.Struct ||
            moduleName == "cxcore" && classDeclaration.Name == "Object")
        {
            writer.WriteLine($"CX_STRUCT_TYPEINFO_DEF({classDeclaration.ToCIdentifier(moduleName, false)}, {nameIdentifier.ToCIdentifier()}, {namespaceIdentifier.ToCIdentifier()}, 0x{GetTypeNameHash(classDeclaration.FullName, moduleName):X}, {flagsString});");
        }
        else if (classDeclaration.ClassType == ClassType.Class)
        {
            if (classDeclaration.IsStatic)
            {
                writer.WriteLine($"CX_STATIC_CLASS_TYPEINFO_DEF({classDeclaration.ToCIdentifier(moduleName, false)}, {nameIdentifier.ToCIdentifier()}, {namespaceIdentifier.ToCIdentifier()}, 0x{GetTypeNameHash(classDeclaration.FullName, moduleName):X}, {flagsString});");
            }
            else
            {
                var baseTypeFullName = classDeclaration.BaseClassType switch
                {
                    NamedType namedType => namedType.ResolvedTypeFullName,
                    _ => new QualifiedIdentifier("cxcore", BuiltInSystemTypes.Object.FullName),
                };
                var baseTypeTypeInfoName = new QualifiedIdentifier(baseTypeFullName, "__typeinfo");
                writer.WriteLine($"CX_CLASS_TYPEINFO_DEF({classDeclaration.ToCIdentifier(moduleName, false)}, {nameIdentifier.ToCIdentifier()}, {namespaceIdentifier.ToCIdentifier()}, {baseTypeTypeInfoName.ToCIdentifier()}, 0x{GetTypeNameHash(classDeclaration.FullName, moduleName):X}, {flagsString});");
            }
        }
        else if (classDeclaration.ClassType == ClassType.Interface)
        {
            writer.WriteLine($"CX_INTERFACE_TYPEINFO_DEF({classDeclaration.ToCIdentifier(moduleName, false)}, {nameIdentifier.ToCIdentifier()}, {namespaceIdentifier.ToCIdentifier()}, 0x{GetTypeNameHash(classDeclaration.FullName, moduleName):X}, {flagsString});");
        }
    }

    private static IEnumerable<string> GetTypeInfoFlags(ClassDeclaration classDeclaration)
    {
        if (classDeclaration.IsStatic)
        {
            yield return "CX_REFLECTION_FLAG_STATIC";
        }
        if (classDeclaration.IsAbstract)
        {
            yield return "CX_REFLECTION_FLAG_ABSTRACT";
        }
        if (classDeclaration.IsFinal)
        {
            yield return "CX_REFLECTION_FLAG_FINAL";
        }

        if (classDeclaration.Visibility == Visibility.Public)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_PUBLIC";
        }
        else if (classDeclaration.Visibility == Visibility.Protected)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_PROTECTED";
        }
        else if (classDeclaration.Visibility == Visibility.Internal)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_INTERNAL";
        }
        else if (classDeclaration.Visibility == Visibility.Private)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_PRIVATE";
        }
        else
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_HIDDEN";
        }

        yield return classDeclaration.ClassType switch
        {
            ClassType.Class => "CX_REFLECTION_FLAG_TYPE_CLASS",
            ClassType.Struct => "CX_REFLECTION_FLAG_TYPE_STRUCT",
            ClassType.Interface => "CX_REFLECTION_FLAG_TYPE_INTERFACE",
            _ => throw new InternalCompilerException($"Unsupported class type: {classDeclaration.ClassType}")
        };
    }

    private static void WriteVTableDefinition(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        string moduleName)
    {
        writer.WriteLine($"CX_BEGIN_VTABLE_DEF({classDeclaration.ToCIdentifier(moduleName, false)})");

        foreach (var slot in classDeclaration.VirtualMethodSlots.OrderBy(slot => slot.Index))
        {
            if (slot.Implementation is null)
            {
                writer.WriteLine("{ .function = (cx_vtable_function)0 },");
            }
            else
            {
                writer.WriteLine($"CX_VTABLE_ENTRY({ToCFunctionName(slot.Implementation, moduleName)})");
            }
        }

        writer.WriteLine("CX_END_VTABLE_DEF;");
    }

    private static void WriteInterfaceVTableDefinition(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        InterfaceDispatchTable table,
        string moduleName)
    {
        var vtableName = GetInterfaceVTableIdentifier(
            classDeclaration,
            table.Interface,
            moduleName).ToCIdentifier();
        writer.WriteLine(
            $"CX_BEGIN_INTERFACE_VTABLE_DEF({vtableName}, " +
            $"{table.Interface.ToCIdentifier(moduleName, false)})");
        foreach (var slot in table.Slots.OrderBy(slot => slot.Index))
        {
            writer.WriteLine(slot.Implementation is null
                ? "{ .function = (cx_vtable_function)0 },"
                : $"CX_VTABLE_ENTRY({GetInterfaceThunkIdentifier(classDeclaration, table.Interface, slot.Index, moduleName).ToCIdentifier()})");
        }
        foreach (var targetInterface in table.Interface.InterfaceUpcastTargets)
        {
            var targetVTable = GetInterfaceVTableIdentifier(
                classDeclaration,
                targetInterface,
                moduleName).ToCIdentifier();
            writer.WriteLine($"{{ .data = {targetVTable} }},");
        }
        writer.WriteLine("CX_END_VTABLE_DEF;");
    }

    private static void WriteInterfaceDispatchThunks(
        IndentingWriter writer,
        IEnumerable<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var classDeclaration in EnumerateClasses(declarations)
            .Where(type => type.ClassType == ClassType.Class))
        {
            foreach (var table in classDeclaration.InterfaceDispatchTables)
            {
                var vtableName = GetInterfaceVTableIdentifier(
                    classDeclaration,
                    table.Interface,
                    moduleName).ToCIdentifier();
                writer.WriteLine($"extern union cx_vtable_entry {vtableName}[];");
            }
        }
        writer.WriteLine();

        foreach (var classDeclaration in EnumerateClasses(declarations)
            .Where(type => type.ClassType == ClassType.Class))
        {
            foreach (var table in classDeclaration.InterfaceDispatchTables)
            {
                foreach (var slot in table.Slots.Where(slot => slot.Implementation is not null))
                {
                    WriteInterfaceDispatchThunk(
                        writer,
                        classDeclaration,
                        table.Interface,
                        slot,
                        moduleName);
                }
            }
        }
    }

    private static void WriteInterfaceDispatchThunk(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        ClassDeclaration interfaceDeclaration,
        InterfaceDispatchSlot slot,
        string moduleName)
    {
        var thunkName = GetInterfaceThunkIdentifier(
            classDeclaration,
            interfaceDeclaration,
            slot.Index,
            moduleName).ToCIdentifier();
        var parameters = new[] { "cx_ptr __root" }.Concat(slot.Parameters.Select(
            parameter => $"{parameter.ParameterType.ToCIdentifier(false)} {parameter.Name}"));
        writer.WriteLine(
            $"static {slot.ReturnType.ToCReturnType(false)} {thunkName}(" +
            $"{string.Join(", ", parameters)}) {{");
        writer.IncreaseIndent();

        var argumentNames = slot.Parameters.Select(parameter => parameter.Name).ToArray();
        string call;
        if (slot.ImplementationFunction is { } implementation &&
            implementation.VirtualSlotIndex is { } virtualSlotIndex)
        {
            var virtualContract = implementation.VirtualContract ?? implementation;
            var receiverConst = virtualContract.Const ? "const " : string.Empty;
            var receiverType =
                $"{receiverConst}{virtualContract.ParentClassDeclaration!.ToCIdentifier(moduleName)}*";
            var parameterTypes = new[] { receiverType }.Concat(
                virtualContract.Parameters.Select(parameter =>
                    parameter.ParameterType.ToCIdentifier(false)));
            var functionPointer =
                $"({virtualContract.ReturnType.ToCReturnType(false)} (*)({string.Join(", ", parameterTypes)}))";
            var receiver = $"({receiverType})__root";
            call = $"({functionPointer}((union cx_vtable_entry*)CX_GET_VTABLE({receiver}))[{virtualSlotIndex}].function)" +
                $"({string.Join(", ", new[] { receiver }.Concat(argumentNames))})";
        }
        else if (slot.ImplementationFunction is { } directImplementation)
        {
            var receiverConst = directImplementation.Const ? "const " : string.Empty;
            var receiver =
                $"({receiverConst}{directImplementation.ParentClassDeclaration!.ToCIdentifier(moduleName)}*)__root";
            call = $"{ToCFunctionName(directImplementation, moduleName)}(" +
                $"{string.Join(", ", new[] { receiver }.Concat(argumentNames))})";
        }
        else
        {
            var accessor = slot.ImplementationAccessor!;
            var property = accessor.ParentPropertyDeclaration;
            var receiverConst = accessor.Const ? "const " : string.Empty;
            var receiver =
                $"({receiverConst}{property.ParentClassDeclaration.ToCIdentifier(moduleName)}*)__root";
            call = $"{ToCPropertyAccessorName(accessor, moduleName)}(" +
                $"{string.Join(", ", new[] { receiver }.Concat(argumentNames))})";
        }

        writer.WriteLine(slot.ReturnType is VoidType ? $"{call};" : $"return {call};");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static QualifiedIdentifier GetInterfaceVTableIdentifier(
        ClassDeclaration classDeclaration,
        ClassDeclaration interfaceDeclaration,
        string moduleName)
    {
        return GetInterfaceVTableIdentifier(
            new QualifiedIdentifier(moduleName, classDeclaration.FullName),
            new QualifiedIdentifier(moduleName, interfaceDeclaration.FullName));
    }

    private static QualifiedIdentifier GetInterfaceVTableIdentifier(
        QualifiedIdentifier className,
        QualifiedIdentifier interfaceName)
    {
        var interfaceParts = className.Parts.FirstOrDefault() == interfaceName.Parts.FirstOrDefault()
            ? interfaceName.Parts.Skip(1).ToArray()
            : interfaceName.Parts;
        return new QualifiedIdentifier(
            className,
            new QualifiedIdentifier("__iface"),
            new QualifiedIdentifier(interfaceParts),
            new QualifiedIdentifier("__vtable"));
    }

    private static QualifiedIdentifier GetInterfaceThunkIdentifier(
        ClassDeclaration classDeclaration,
        ClassDeclaration interfaceDeclaration,
        int slotIndex,
        string moduleName)
    {
        var vtableName = GetInterfaceVTableIdentifier(
            classDeclaration,
            interfaceDeclaration,
            moduleName);
        return new QualifiedIdentifier(vtableName, $"slot_{slotIndex}");
    }

    private static IEnumerable<ClassDeclaration> EnumerateClasses(
        IEnumerable<DeclarationBase> declarations)
    {
        foreach (var classDeclaration in declarations.OfType<ClassDeclaration>())
        {
            yield return classDeclaration;
            foreach (var nested in EnumerateClasses(
                classDeclaration.MemberDeclarations.Declarations))
            {
                yield return nested;
            }
        }
    }

    private static List<DeclarationBase> GetDeclarations(CxProject project)
    {
        List<DeclarationBase> declarations = [];

        foreach (var compilationContext in project.CompilationContexts)
        {
            foreach (var declaration in compilationContext.DeclarationScope.Declarations)
            {
                if (declaration is ClassDeclaration classDeclaration)
                {
                    declarations.Add(classDeclaration);
                }
                else if (declaration is FunctionDeclaration functionDeclaration)
                {
                    declarations.Add(functionDeclaration);
                }
                else if (declaration is EnumDeclaration enumDeclaration)
                {
                    declarations.Add(enumDeclaration);
                }
                else
                {
                    throw new InternalCompilerException(
                        $"Unsupported declaration type: {declaration.GetType().Name} in project '{project.Name}'");
                }
            }
        }

        var cxcoreTypeOrder = new Dictionary<string, int>
        {
            { "Object", -1000 },
            { "Nullable", -900 },
            { "TypeInfo", -800 },
            { "VersionInfo", -700 }
        }; // TODO: Remove this hack for cxcore

        var result = declarations.Order(Comparer<DeclarationBase>.Create((x, y) =>
        {
            if (x is ClassDeclaration xClassDeclaration && y is ClassDeclaration yClassDeclaration)
            {
                var depthComparison = GetInheritanceDepth(xClassDeclaration)
                    .CompareTo(GetInheritanceDepth(yClassDeclaration));
                if (depthComparison != 0)
                {
                    return depthComparison;
                }
                if (project.Name == "cxcore") // TODO: Remove this hack for cxcore
                {
                    if (cxcoreTypeOrder.ContainsKey(x.Name) && !cxcoreTypeOrder.ContainsKey(y.Name))
                    {
                        return -1;
                    }
                    else if (!cxcoreTypeOrder.ContainsKey(x.Name) && cxcoreTypeOrder.ContainsKey(y.Name))
                    {
                        return 1;
                    }
                    else if (cxcoreTypeOrder.ContainsKey(x.Name) && cxcoreTypeOrder.ContainsKey(y.Name))
                    {
                        return cxcoreTypeOrder[x.Name].CompareTo(cxcoreTypeOrder[y.Name]);
                    }
                }

                if (ReferenceEquals(xClassDeclaration.BaseClassDeclaration, yClassDeclaration))
                {
                    return 1;
                }
                else if (ReferenceEquals(yClassDeclaration.BaseClassDeclaration, xClassDeclaration))
                {
                    return -1;
                }
                else
                {
                    return QualifiedIdentifier.Compare(xClassDeclaration.FullName, yClassDeclaration.FullName);
                }
            }
            else if (x.GetType() == y.GetType())
            {
                return QualifiedIdentifier.Compare(x.FullName, y.FullName);
            }
            return GetDeclarationOrder(x).CompareTo(GetDeclarationOrder(y));
        })).ToList();
        return result;

        static int GetDeclarationOrder(DeclarationBase declaration) => declaration switch
        {
            EnumDeclaration => 0,
            ClassDeclaration => 1,
            FunctionDeclaration => 2,
            _ => 3,
        };

        static int GetInheritanceDepth(ClassDeclaration declaration)
        {
            var depth = 0;
            while (declaration.BaseClassDeclaration is { } baseClass)
            {
                depth++;
                declaration = baseClass;
            }
            return depth;
        }
    }

    private static int GetNameOverrideIndex(FunctionDeclaration functionDeclaration, IReadOnlyCollection<DeclarationBase> declarations)
    {
        var nameOverrides = declarations
            .OfType<FunctionDeclaration>()
            .Where(fd => fd.FullName == functionDeclaration.FullName)
            .ToList();
        return nameOverrides.IndexOf(functionDeclaration) + 1;
    }

    private static string ToCIdentifier(this ClassDeclaration classDeclaration, string moduleName, bool includeStruct = true)
    {
        var fullName = new QualifiedIdentifier(moduleName, classDeclaration.FullName);
        return $"{(includeStruct ? "struct " : "")}{fullName.ToCIdentifier()}";
    }

    private static string ToCIdentifier(this EnumDeclaration enumDeclaration, string moduleName)
    {
        return new QualifiedIdentifier(moduleName, enumDeclaration.FullName).ToCIdentifier();
    }

    private static string ToCIdentifier(this EnumMemberDeclaration member, string moduleName)
    {
        return new QualifiedIdentifier(moduleName, member.FullName).ToCIdentifier();
    }

    private static string ToCStorageType(TypeBase type)
    {
        type = type is ConstType constType ? constType.UnderlyingType : type;
        return type switch
        {
            ObjectType => "struct CX_ID_3(cxcore, System, Object)",
            NamedType { ClassType: ClassType.Class } namedType =>
                $"struct {namedType.ResolvedTypeFullName.ToCIdentifier()}",
            _ => type.ToCIdentifier(false).TrimEnd('*', ' '),
        };
    }

    private static string ToCIdentifier(this FunctionDeclaration functionDeclaration, string moduleName, int nameOverrideIndex)
    {
        var name = nameOverrideIndex > 1
            ? new QualifiedIdentifier(functionDeclaration.FullName, $"_{nameOverrideIndex}")
            : functionDeclaration.FullName;
        var fullName = new QualifiedIdentifier(moduleName, name);
        return $"{functionDeclaration.ReturnType.ToCReturnType(false /* TODO */)} {fullName.ToCIdentifier()}";
    }

    private static string ToCFunctionName(
        FunctionDeclaration functionDeclaration,
        string moduleName)
    {
        var declarations = functionDeclaration.ParentClassDeclaration is null
            ? Array.Empty<DeclarationBase>()
            : functionDeclaration.ParentClassDeclaration.MemberDeclarations.Declarations.ToArray();
        var nameOverrideIndex = GetNameOverrideIndex(functionDeclaration, declarations);
        var name = nameOverrideIndex > 1
            ? new QualifiedIdentifier(functionDeclaration.FullName, $"_{nameOverrideIndex}")
            : functionDeclaration.FullName;
        return new QualifiedIdentifier(moduleName, name).ToCIdentifier();
    }

    private static string ToCIdentifier(this PropertyAccessorDeclaration propertyAccessorDeclaration, string moduleName)
    {
        var returnType = propertyAccessorDeclaration.Name == "set"
            ? BuiltInSystemTypes.Void
            : propertyAccessorDeclaration.ParentPropertyDeclaration.Type;
        return $"{returnType.ToCReturnType(false)} {ToCPropertyAccessorName(propertyAccessorDeclaration, moduleName)}";
    }

    private static string ToCPropertyAccessorName(
        PropertyAccessorDeclaration propertyAccessorDeclaration,
        string moduleName)
    {
        var accessorName = $"__{(propertyAccessorDeclaration.Const ? "const_" : "")}{propertyAccessorDeclaration.Name}";
        var name = new QualifiedIdentifier(
            propertyAccessorDeclaration.ParentPropertyDeclaration.FullName,
            accessorName);
        return new QualifiedIdentifier(moduleName, name).ToCIdentifier();
    }

    private static string ToCIdentifier(this TypeBase typeBase, bool @const)
    {
        var constString = @const ? "const" : "";
        return typeBase switch
        {
            ConstType constType => constType.UnderlyingType.ToCIdentifier(true),
            BoolType => "cx_bool",
            CharType => "cx_char",

            SByteType => "cx_sbyte",
            ShortType => "cx_short",
            IntType => "cx_int",
            LongType => "cx_long",

            ByteType => "cx_byte",
            UShortType => "cx_ushort",
            UIntType => "cx_uint",
            ULongType => "cx_ulong",

            FloatType => "cx_float",
            DoubleType => "cx_double",

            ObjectType => $"{constString} struct CX_ID_3(cxcore, System, Object)*",
            StringType => $"{constString} struct CX_ID_3(cxcore, System, String)*",
            PtrType => $"{constString} cx_ptr",

            FunctionType => throw new NotImplementedException(), // TODO
            VoidType => "void",
            NullType => "cx_ptr",

            ArrayType => $"{constString} struct CX_ID_3(cxcore, System, Array)*",
            NullableType => $"{constString} struct CX_ID_3(cxcore, System, Nullable)",

            NamedType namedType when namedType.ClassType == ClassType.Struct => $"{constString} struct {namedType.ResolvedTypeFullName.ToCIdentifier()}",
            NamedType namedType when namedType.ClassType == ClassType.Class => $"{constString} struct {namedType.ResolvedTypeFullName.ToCIdentifier()}*",
            NamedType { ClassType: ClassType.Interface } => $"{constString} struct cx_iface_ref",
            NamedType namedType when namedType.ClassType == ClassType.Enum => $"{constString} {namedType.ResolvedTypeFullName.ToCIdentifier()}",

            _ => "_unknowntype_" // TODO: throw below exception for unsupported types
            //_ => throw new InternalCompilerException($"Unsupported type: {typeBase.GetType().Name}"),
        };
    }

    private static string ToCIdentifier(this QualifiedIdentifier qualifiedIdentifier)
    {
        if (qualifiedIdentifier.IsEmpty)
        {
            throw new InternalCompilerException("QualifiedIdentifier cannot be empty");
        }

        if (qualifiedIdentifier.Parts.Length == 1)
        {
            return qualifiedIdentifier.Parts[0];
        }

        return $"CX_ID_{qualifiedIdentifier.Parts.Length}({string.Join(", ", qualifiedIdentifier.Parts)})";
    }

    private static string ToCReturnType(this TypeBase typeBase, bool @const)
    {
        if (IsGenericValueType(typeBase))
        {
            return "void";
        }

        return typeBase.ToCIdentifier(@const);
    }

    private static bool IsGenericValueType(TypeBase typeBase)
    {
        var effectiveType = typeBase is ConstType constType
            ? constType.UnderlyingType
            : typeBase;
        return effectiveType is GenericType ||
            effectiveType is NamedType namedType && namedType.GenericParams.Length > 0;
    }

    private static ulong GetTypeNameHash(QualifiedIdentifier typeName, string moduleName)
    {
        var fullName = new QualifiedIdentifier(moduleName, typeName);
        var fullNameString = fullName.ToString();
        byte[] bytes = Encoding.Unicode.GetBytes(fullNameString);
        byte[] hash = SHA256.HashData(bytes);
        return
            BitConverter.ToUInt64(hash, 0) ^
            BitConverter.ToUInt64(hash, 8) ^
            BitConverter.ToUInt64(hash, 16) ^
            BitConverter.ToUInt64(hash, 24);
    }
}
