using CxCompiler.Model;
using CxCompiler.Model.Common;
using CxCompiler.Model.Expressions;
using CxCompiler.Model.Project;
using CxCompiler.Model.Statements;
using CxCompiler.Model.Types;
using CxCompiler.Model.Types.BuiltInTypes;
using System.Security.Cryptography;
using System.Text;

namespace CxCompiler.OutputGenerators;

public static partial class CCodeOutputGenerator
{
    public static void GenerateOutput(CxProject project, string filePath)
    {
        if (project == null)
        {
            throw new InternalCompilerException("Project is null");
        }

        WriteCMakeListsFile(project, Path.Combine(Path.GetDirectoryName(filePath)!, "CMakeLists.txt"));
        WriteProjectHeaderFile(project, Path.Combine(Path.GetDirectoryName(filePath)!, $"{project.Name}.h"));
        WriteProjectSourceFile(project, Path.Combine(Path.GetDirectoryName(filePath)!, $"{project.Name}.c"));
    }

    private static void WriteCMakeListsFile(CxProject project, string outputFilePath)
    {
        if (Path.Exists(outputFilePath)) return;

        using var fileWriter = new StreamWriter(outputFilePath);

        fileWriter.WriteLine("cmake_minimum_required(VERSION 3.31)");
        fileWriter.WriteLine($"project({project.Name})");
        fileWriter.WriteLine();

        switch (project.Type)
        {
            case CxProjectType.Library:
                fileWriter.WriteLine($"add_library({project.Name} SHARED {project.Name}.c)");
                break;

            case CxProjectType.Executable:
                fileWriter.WriteLine($"add_executable({project.Name} {project.Name}.c)");
                break;

            default:
                throw new ArgumentOutOfRangeException($"Invalid CxProjectType {project.Type}");
        }

        fileWriter.Flush();
        fileWriter.Close();
    }


    private static void WriteProjectHeaderFile(CxProject project, string outputFilePath)
    {
        using var fileWriter = new StreamWriter(outputFilePath);
        var writer = new IndentingWriter(fileWriter);

        writer.WriteLine($"// This is an autogenerated C header file for project '{project.Name}'");
        writer.WriteLine();

        string headerGuardName = project.Name.ToUpperInvariant().Replace('.', '_');
        writer.WriteLine($"#ifndef _{headerGuardName}_H_");
        writer.WriteLine($"#define _{headerGuardName}_H_");
        writer.WriteLine();
        writer.WriteLine(project.Name == "cxcore"
            ? "#include <cx.h>"
            : "#include <cxcore.h>");
        writer.WriteLine();

        var declarations = GetDeclarations(project);

        writer.WriteLine("//");
        writer.WriteLine("// Forward type declarations");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteTypesForwardDeclarations(writer, declarations, project.Name);
        foreach (var instance in project.GenericTypeInstances.Where(item =>
            RequiresClosedValueLayout(item.Type)))
        {
            writer.WriteLine($"struct {instance.Type.ConstructedIdentity!.CIdentifier};");
        }
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Type declarations");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteTypesDeclarations(writer, declarations, project.Name);
        WriteClosedValueTypeDeclarations(writer, project.GenericTypeInstances);
        foreach (var instance in project.GenericTypeInstances.OrderBy(item =>
            item.Type.ConstructedIdentity!.CanonicalName, StringComparer.Ordinal))
        {
            ValidateClosedReferenceLayout(instance.Type, instance.Declaration);
            writer.WriteLine($"CX_VTABLE_DECL({instance.Type.ConstructedIdentity!.CIdentifier});");
            writer.WriteLine($"CX_TYPEINFO_DECL({instance.Type.ConstructedIdentity.CIdentifier});");
        }
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Function and property declarations");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteFunctionsForwardDeclarations(writer, declarations, project.Name);
        WriteGenericFunctionDeclarations(writer, project.GenericFunctionInstances);
        writer.WriteLine();

        writer.WriteLine();
        writer.WriteLine($"#endif // _{headerGuardName}_H_");

        fileWriter.Flush();
        fileWriter.Close();
    }

    private static void WriteTypesForwardDeclarations(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var declaration in declarations)
        {
            if (declaration is EnumDeclaration enumDeclaration)
            {
                var enumName = enumDeclaration.ToCIdentifier(moduleName);
                writer.WriteLine($"typedef enum {enumName} {{");
                writer.IncreaseIndent();
                for (var index = 0; index < enumDeclaration.Members.Count; index++)
                {
                    var member = enumDeclaration.Members[index];
                    var value = member.Value is null
                        ? string.Empty
                        : $" = {member.Value.SourceText}";
                    var comma = index + 1 < enumDeclaration.Members.Count ? "," : string.Empty;
                    writer.WriteLine($"{member.ToCIdentifier(moduleName)}{value}{comma}");
                }
                writer.DecreaseIndent();
                writer.WriteLine($"}} {enumName};");
                writer.WriteLine($"CX_TYPEINFO_DECL({enumName});");
            }
            else if (declaration is ClassDeclaration classDeclaration)
            {
                writer.WriteLine($"{classDeclaration.ToCIdentifier(moduleName)};");

                var memberDeclarations = classDeclaration.MemberDeclarations.Declarations
                    .Where(x => x is ClassDeclaration or EnumDeclaration)
                    .ToArray();
                if (memberDeclarations.Length != 0)
                {
                    WriteTypesForwardDeclarations(writer, memberDeclarations, moduleName);
                }
            }
        }
    }

    private static void WriteTypesDeclarations(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var declaration in declarations)
        {
            if (declaration is ClassDeclaration classDeclaration)
            {
                if (classDeclaration.ClassType == ClassType.Class && classDeclaration.IsStatic)
                {
                    writer.WriteLine($"CX_STATIC_TYPE_DEF({classDeclaration.ToCIdentifier(moduleName, false)});");
                }
                else
                {
                    writer.WriteLine($"CX_TYPE_DEF({classDeclaration.ToCIdentifier(moduleName, false)}) {{");

                    writer.IncreaseIndent();

                    if (moduleName == "cxcore" && classDeclaration.Name == "Object")
                    {
                        writer.WriteLine("void* __vtable;");
                    }
                    else if (classDeclaration.ClassType == ClassType.Interface)
                    {
                        writer.WriteLine("void* __vtable;");
                        writer.WriteLine("void* __root;");
                    }
                    else if (classDeclaration.ClassType == ClassType.Class)
                    {
                        var baseType = classDeclaration.BaseClassType ?? BuiltInSystemTypes.Object;
                        writer.WriteLine($"{ToCStorageType(baseType)} __base;");
                    }

                    var fieldMemberDeclarations = classDeclaration.MemberDeclarations.Declarations
                        .OfType<FieldDeclaration>()
                        .Where(field => !field.IsStatic)
                        .ToArray();
                    if (!fieldMemberDeclarations.Any() &&
                        classDeclaration.ClassType == ClassType.Struct)
                    {
                        writer.WriteLine("cx_byte __dummy;");
                    }
                    else
                    {
                        foreach (var fieldDeclaration in fieldMemberDeclarations)
                        {
                            var fieldType = fieldDeclaration.Type is GenericType &&
                                classDeclaration.GenericTypeNames.Length > 0
                                ? "cx_ptr"
                                : fieldDeclaration.Type.ToCIdentifier(false);
                            writer.WriteLine($"{fieldType} {fieldDeclaration.Name};");
                        }
                    }

                    writer.DecreaseIndent();
                    writer.WriteLine("};");

                }

                foreach (var staticField in classDeclaration.MemberDeclarations.Declarations
                    .OfType<FieldDeclaration>()
                    .Where(field => field.IsStatic))
                {
                    writer.WriteLine(
                        $"extern {staticField.Type.ToCIdentifier(false)} " +
                        $"{GetStaticFieldIdentifier(staticField, moduleName)};");
                }

                var classMemberDeclarations = classDeclaration.MemberDeclarations.Declarations
                    .OfType<ClassDeclaration>()
                    .ToArray();
                if (classMemberDeclarations.Length != 0)
                {
                    WriteTypesDeclarations(writer, classMemberDeclarations, moduleName);
                }
            }
        }
    }

    private static void WriteFunctionsForwardDeclarations(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        bool exportable;
        bool isFirstParameter;

        foreach (var declaration in declarations)
        {
            switch (declaration)
            {
                case ClassDeclaration classDeclaration:
                    var memberDeclarations = classDeclaration.MemberDeclarations.Declarations.ToArray();
                    if (memberDeclarations.Length != 0)
                    {
                        WriteFunctionsForwardDeclarations(writer, memberDeclarations, moduleName);
                    }

                    break;

                case FunctionDeclaration functionDeclaration:
                    if (functionDeclaration.GenericTypeNames.Length > 0)
                    {
                        break;
                    }
                    if (functionDeclaration.ParentClassDeclaration?.ClassType == ClassType.Interface)
                    {
                        break;
                    }
                    exportable =
                        (
                            functionDeclaration.ParentClassDeclaration == null &&
                            functionDeclaration.MemberModifiers.Contains(MemberModifier.Public)
                        ) ||
                        (
                            functionDeclaration.ParentClassDeclaration?.ClassType == ClassType.Struct &&
                            functionDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            functionDeclaration.ParentClassDeclaration?.Visibility == Visibility.Public
                        ) ||
                        (
                            functionDeclaration.ParentClassDeclaration?.ClassType == ClassType.Class &&
                            functionDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            functionDeclaration.ParentClassDeclaration?.Visibility == Visibility.Public
                        ); // TODO: Traverse up all class hierarchy
                    var nameOverrideIndex = GetNameOverrideIndex(functionDeclaration, declarations);

                    writer.WriteIndent();
                    writer.Write($"extern {(exportable ? "CX_EXPORT " : "")}{functionDeclaration.ToCIdentifier(moduleName, nameOverrideIndex)}(");
                    writer.IncreaseIndent();

                    isFirstParameter = true;
                    if (!functionDeclaration.IsStatic)
                    {
                        writer.WriteNewLine();
                        writer.WriteIndent();
                        var receiverConst = functionDeclaration.Const ? "const " : string.Empty;
                        writer.Write($"{receiverConst}{functionDeclaration.ParentClassDeclaration!.ToCIdentifier(moduleName)}* __this");
                        isFirstParameter = false;
                    }

                    var hasGenericReturn = IsGenericValueType(functionDeclaration.ReturnType) &&
                        !ReturnsGenericClassReference(functionDeclaration);
                    if (functionDeclaration.Parameters.Count > 0)
                    {
                        if (!isFirstParameter)
                        {
                            writer.Write(",");
                        }

                        writer.WriteNewLine();

                        for (int i = 0; i < functionDeclaration.Parameters.Count; i++)
                        {
                            FunctionParameter? parameter = functionDeclaration.Parameters[i];

                            writer.WriteIndent();
                            writer.Write($"{ToCParameterType(parameter.ParameterType)} {parameter.Name}");

                            if (i != functionDeclaration.Parameters.Count - 1 || hasGenericReturn)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();
                        }
                    }

                    if (hasGenericReturn)
                    {
                        if (functionDeclaration.Parameters.Count == 0)
                        {
                            if (!isFirstParameter)
                            {
                                writer.Write(",");
                            }
                            writer.WriteNewLine();
                        }
                        writer.WriteIndent();
                        writer.Write("void* __returnValue");
                        writer.WriteNewLine();
                    }
                    else if (functionDeclaration.Parameters.Count == 0 && !isFirstParameter)
                    {
                        writer.WriteLine();
                    }

                    writer.DecreaseIndent();
                    writer.WriteLine(");");
                    break;

                case PropertyDeclaration propertyDeclaration:
                    if (propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Interface)
                    {
                        break;
                    }
                    foreach (var propertyAccessorDeclaration in propertyDeclaration.PropertyAccessorDeclarations)
                    {
                        exportable =
                        (
                            propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Interface
                        ) ||
                        (
                            propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Struct &&
                            propertyDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            propertyDeclaration.ParentClassDeclaration.Visibility == Visibility.Public
                        ) ||
                        (
                            propertyDeclaration.ParentClassDeclaration.ClassType == ClassType.Class &&
                            propertyDeclaration.MemberModifiers.Contains(MemberModifier.Public) &&
                            propertyDeclaration.ParentClassDeclaration.Visibility == Visibility.Public
                        );

                        writer.WriteIndent();
                        writer.Write($"extern {(exportable ? "CX_EXPORT " : "")}{propertyAccessorDeclaration.ToCIdentifier(moduleName)}(");
                        writer.IncreaseIndent();

                        isFirstParameter = true;
                        if (!propertyDeclaration.IsStatic)
                        {
                            writer.WriteNewLine();
                            writer.WriteIndent();
                            var receiverConst = propertyAccessorDeclaration.Const ? "const " : string.Empty;
                            writer.Write($"{receiverConst}{propertyDeclaration.ParentClassDeclaration.ToCIdentifier(moduleName)}* __this");
                            isFirstParameter = false;
                        }

                        if (propertyAccessorDeclaration.Parameters.Count > 0)
                        {
                            if (!isFirstParameter)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();

                            for (int i = 0; i < propertyAccessorDeclaration.Parameters.Count; i++)
                            {
                                FunctionParameter? parameter = propertyAccessorDeclaration.Parameters[i];
                                isFirstParameter = false;

                                writer.WriteIndent();
                                writer.Write($"{parameter.ParameterType.ToCIdentifier(@const: false)} {parameter.Name}");

                                if (i != propertyAccessorDeclaration.Parameters.Count - 1)
                                {
                                    writer.Write(",");
                                }

                                writer.WriteNewLine();
                            }
                        }

                        var hasGenericValue = IsGenericValueType(propertyDeclaration.Type);
                        if (propertyAccessorDeclaration.Name == "set")
                        {
                            if (!isFirstParameter)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();
                            writer.WriteIndent();
                            writer.Write(hasGenericValue
                                ? "void* value"
                                : $"{propertyDeclaration.Type.ToCIdentifier(false)} value");
                            isFirstParameter = false;
                        }
                        else if (hasGenericValue &&
                            !ReturnsGenericClassPropertyReference(propertyAccessorDeclaration))
                        {
                            if (!isFirstParameter)
                            {
                                writer.Write(",");
                            }

                            writer.WriteNewLine();

                            writer.WriteIndent();
                            writer.Write("void* __returnValue");
                            isFirstParameter = false;
                        }

                        if (!isFirstParameter)
                        {
                            writer.WriteLine();
                        }

                        writer.DecreaseIndent();
                        writer.WriteLine(");");
                    }

                    break;
            }
        }
    }

    private static void WriteGenericFunctionDeclarations(
        IndentingWriter writer,
        IEnumerable<CxCompiler.Semantics.FunctionSymbol> instances)
    {
        foreach (var instance in instances.OrderBy(item => item.SpecializationName, StringComparer.Ordinal))
        {
            var name = instance.SpecializationName!;
            var declaration = instance.Declaration!;
            var parameters = GetGenericFunctionParameters(instance);
            var export = declaration.MemberModifiers.Contains(MemberModifier.Public)
                ? "CX_EXPORT "
                : string.Empty;
            writer.WriteLine($"extern {export}{instance.ReturnType.ToCIdentifier(false)} " +
                $"{name}({string.Join(", ", parameters)});");
        }
    }

    private static IReadOnlyList<string> GetGenericFunctionParameters(
        CxCompiler.Semantics.FunctionSymbol instance)
    {
        var declaration = instance.Declaration!;
        var parameters = new List<string>();
        if (!declaration.IsStatic)
        {
            var receiverConst = declaration.Const ? "const " : string.Empty;
            parameters.Add($"{receiverConst}" +
                $"{declaration.ParentClassDeclaration!.ToCIdentifier(instance.ModuleName)}* __this");
        }
        parameters.AddRange(declaration.Parameters.Zip(instance.ParameterTypes)
            .Select(pair => $"{pair.Second.ToCIdentifier(false)} {pair.First.Name}"));
        return parameters;
    }

    private static void WriteProjectSourceFile(CxProject project, string outputFilePath)
    {
        using var fileWriter = new StreamWriter(outputFilePath);
        var writer = new IndentingWriter(fileWriter);

        writer.WriteLine($"// This is an autogenerated C source file for project '{project.Name}'");
        writer.WriteLine();
        writer.WriteLine($"#include \"{project.Name}.h\"");
        writer.WriteLine();

        var declarations = GetDeclarations(project);

        writer.WriteLine("//");
        writer.WriteLine("// Strings");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteStrings(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Static fields");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteStaticFields(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Interface dispatch thunks");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteInterfaceDispatchThunks(writer, declarations, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// TypeInfos");
        writer.WriteLine("//");
        WriteTypeInfos(writer, declarations, project.Name);
        WriteClosedGenericTypeInfos(writer, project.GenericTypeInstances, project.Name);
        writer.WriteLine();

        writer.WriteLine("//");
        writer.WriteLine("// Functions");
        writer.WriteLine("//");
        writer.WriteLine();
        WriteFunctionDefinitions(writer, declarations, project.Name);
        WriteGenericFunctionDefinitions(writer, project.GenericFunctionInstances);

        fileWriter.Flush();
        fileWriter.Close();
    }

    private static void WriteStrings(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        List<QualifiedIdentifier> namespaces = [];

        foreach (var declaration in EnumerateClasses(declarations))
        {
            var nameIdentifier = new QualifiedIdentifier("__name", declaration.FullName);
            writer.WriteLine($"CX_STRING_DEF({nameIdentifier.ToCIdentifier()}, \"{declaration.Name}\");");

            var @namespace = declaration.Namespace;
            if (!namespaces.Contains(@namespace))
            {
                namespaces.Add(@namespace);
            }
        }

        foreach (var declaration in EnumerateEnums(declarations))
        {
            var nameIdentifier = new QualifiedIdentifier("__name", declaration.FullName);
            writer.WriteLine($"CX_STRING_DEF({nameIdentifier.ToCIdentifier()}, \"{declaration.Name}\");");
            if (!namespaces.Contains(declaration.Namespace))
            {
                namespaces.Add(declaration.Namespace);
            }
        }

        foreach (var @namespace in namespaces)
        {
            var namespaceIdentifier = new QualifiedIdentifier("__namespace", @namespace);
            writer.WriteLine($"CX_STRING_DEF({namespaceIdentifier.ToCIdentifier()}, \"{@namespace}\");");
        }

        var functionLiterals = EnumerateFunctions(declarations)
            .Where(function => function.Body is not null)
            .SelectMany(function => function.Body!)
            .SelectMany(EnumerateStringLiterals);
        var fieldLiterals = EnumerateFields(declarations)
            .Where(field => field.Initializer is LiteralExpression { IsString: true })
            .Select(field => (LiteralExpression)field.Initializer!);
        foreach (var literal in functionLiterals
            .Concat(fieldLiterals)
            .DistinctBy(literal => literal.SourceText))
        {
            writer.WriteLine(
                $"CX_STRING_DEF({GetStringIdentifier(literal, moduleName).ToCIdentifier()}, {literal.SourceText});");
        }
    }

    private static void WriteStaticFields(
        IndentingWriter writer,
        IEnumerable<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var field in EnumerateFields(declarations).Where(field => field.IsStatic))
        {
            var initializer = field.Initializer is null
                ? string.Empty
                : $" = {ToCFieldInitializer(field.Initializer, moduleName)}";
            writer.WriteLine(
                $"{field.Type.ToCIdentifier(false)} {GetStaticFieldIdentifier(field, moduleName)}{initializer};");
        }
    }

    private static IEnumerable<FieldDeclaration> EnumerateFields(
        IEnumerable<DeclarationBase> declarations)
    {
        foreach (var declaration in declarations)
        {
            if (declaration is FieldDeclaration field)
            {
                yield return field;
            }
            else if (declaration is ClassDeclaration classDeclaration)
            {
                foreach (var nested in EnumerateFields(classDeclaration.MemberDeclarations.Declarations))
                {
                    yield return nested;
                }
            }
        }
    }

    private static string GetStaticFieldIdentifier(
        FieldDeclaration field,
        string moduleName)
    {
        return new QualifiedIdentifier(moduleName, field.FullName).ToCIdentifier();
    }

    private static string ToCFieldInitializer(ExpressionBase expression, string moduleName)
    {
        return expression switch
        {
            LiteralExpression { IsString: true } literal =>
                $"&{GetStringIdentifier(literal, moduleName).ToCIdentifier()}",
            LiteralExpression { SourceText: "true" } => "CX_TRUE",
            LiteralExpression { SourceText: "false" } => "CX_FALSE",
            LiteralExpression { SourceText: "null" } literal => ToCNullLiteral(literal),
            LiteralExpression literal => literal.SourceText,
            _ => throw new InternalCompilerException(
                $"Field initializer '{expression.GetType().Name}' is not supported."),
        };
    }

    private static QualifiedIdentifier GetStringIdentifier(
        LiteralExpression literal,
        string moduleName)
    {
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(literal.SourceText));
        return new QualifiedIdentifier(moduleName, $"__string_{Convert.ToHexString(hash.AsSpan(0, 8))}");
    }

    private static void WriteTypeInfos(
        IndentingWriter writer,
        IReadOnlyCollection<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var classDeclaration in EnumerateClasses(declarations))
        {
            writer.WriteLine();
            if (classDeclaration.ClassType == ClassType.Class && classDeclaration.IsStatic)
            {
                WriteReflectionMetadata(writer, classDeclaration, moduleName);
                WriteTypeInfoDefinition(writer, classDeclaration, moduleName);
                continue;
            }

            WriteVTableDefinition(writer, classDeclaration, moduleName);
            foreach (var table in classDeclaration.InterfaceDispatchTables)
            {
                WriteInterfaceVTableDefinition(writer, classDeclaration, table, moduleName);
            }
            WriteInterfaceRuntimeMap(writer, classDeclaration, moduleName);
            WriteReflectionMetadata(writer, classDeclaration, moduleName);
            WriteTypeInfoDefinition(writer, classDeclaration, moduleName);
        }

        foreach (var enumDeclaration in EnumerateEnums(declarations))
        {
            writer.WriteLine();
            WriteEnumTypeInfoDefinition(writer, enumDeclaration, moduleName);
        }
    }

    private static void ValidateClosedReferenceLayout(
        NamedType type,
        ClassDeclaration declaration)
    {
        if (RequiresClosedValueLayout(type))
        {
            ValidateClosedValueLayout(declaration);
            return;
        }
        var members = declaration.MemberDeclarations.Declarations;
        var constructors = members.OfType<ConstructorDeclaration>().ToArray();
        var fields = members.OfType<FieldDeclaration>().ToArray();
        var methods = members.OfType<FunctionDeclaration>()
            .Where(function => function is not ConstructorDeclaration).ToArray();
        var properties = members.OfType<PropertyDeclaration>().ToArray();
        var supportedConstructor = constructors.Length == 0 ||
            constructors.Length == 1 && constructors[0] is { } constructor &&
            (constructor.Body is { Count: 0 } && constructor.Parameters.Count == 0 ||
                IsReferenceFieldAssignments(constructor, fields)) &&
            (constructor.Initializer is null ||
                constructor.Initializer is
                {
                    Kind: ConstructorInitializerKind.Base,
                    Arguments.Count: 0,
                });
        var supportedFields = fields.All(field =>
        {
            if (field.IsStatic || field.Initializer is not null)
            {
                return false;
            }
            if (field.Type is ArrayType { ElementType: GenericType arrayParameter })
            {
                return declaration.GenericTypeNames.Contains(arrayParameter.Name);
            }
            if (field.Type is GenericType parameter)
            {
                var index = Array.IndexOf(declaration.GenericTypeNames, parameter.Name);
                return index >= 0 &&
                    type.TypeArguments[index] is NamedType { ClassType: ClassType.Class };
            }
            return false;
        });
        var supportedMethods = methods.All(method =>
            !method.IsStatic && method.GenericTypeNames.Length == 0 &&
            method.VirtualSlotIndex is null &&
            (method.ReturnType is VoidType && IsReferenceFieldSetter(method, fields) ||
                IsReferenceFieldGetter(method, fields)));
        var supportedProperties = properties.All(property =>
            !property.IsStatic && property.Type is GenericType &&
            property.PropertyAccessorDeclarations.Count is >= 1 and <= 2 &&
            property.PropertyAccessorDeclarations.Select(accessor => accessor.Name)
                .Distinct().Count() == property.PropertyAccessorDeclarations.Count &&
            property.PropertyAccessorDeclarations.All(accessor =>
                IsReferenceFieldPropertyAccessor(property, accessor, fields)));
        if (declaration.ClassType != ClassType.Class || declaration.IsStatic ||
            members.Count != constructors.Length + fields.Length + methods.Length + properties.Length ||
            !supportedConstructor || !supportedFields || !supportedMethods ||
            !supportedProperties ||
            declaration.BaseTypes.Count != 0 ||
            declaration.VirtualMethodSlots.Count != 0 ||
            declaration.InterfaceDispatchTables.Count != 0)
        {
            throw new CxCompiler.Model.Errors.CompilationErrorException(
                $"Closed runtime metadata for generic type '{declaration.FullName}' " +
                "currently requires an empty class, T[] fields, or T fields with " +
                "class-reference arguments; it also requires at most an empty " +
                "parameterless constructor, or one assignment per reference " +
                "constructor parameter, or a void method with a " +
                "single-field assignment, or a T getter returning a T field, " +
                "or a T property reading and writing a T field, and no explicit bases.");
        }
    }

    private static bool RequiresClosedValueLayout(NamedType type) =>
        type.ConstructedIdentity is not null &&
        type.TypeArguments is [NamedType { ClassType: ClassType.Struct,
            TypeArguments.Count: 0 }];

    private static void ValidateClosedValueLayout(ClassDeclaration declaration)
    {
        var members = declaration.MemberDeclarations.Declarations;
        var fields = members.OfType<FieldDeclaration>().ToArray();
        var constructors = members.OfType<ConstructorDeclaration>().ToArray();
        if (declaration.ClassType != ClassType.Class || declaration.IsStatic ||
            declaration.GenericTypeNames.Length != 1 ||
            members.Count != fields.Length + constructors.Length ||
            fields.Length > 1 || constructors.Length > 1 ||
            fields.Length == 1 &&
                (constructors.Length != 1 || fields[0].IsStatic ||
                 fields[0].Initializer is not null ||
                 fields[0].Type is not GenericType parameter ||
                 parameter.Name != declaration.GenericTypeNames[0]) ||
            constructors.Length == 1 &&
                (constructors[0].Parameters.Count != 0 ||
                 constructors[0].Body is not { Count: 0 } ||
                 constructors[0].Initializer is not null and not
                    { Kind: ConstructorInitializerKind.Base, Arguments.Count: 0 }) ||
            declaration.BaseTypes.Count != 0 ||
            declaration.VirtualMethodSlots.Count != 0 ||
            declaration.InterfaceDispatchTables.Count != 0)
        {
            throw new CxCompiler.Model.Errors.CompilationErrorException(
                $"Closed value layout for generic type '{declaration.FullName}' " +
                "requires an empty class or one direct T field with an " +
                "empty parameterless constructor.");
        }
    }

    private static void WriteClosedValueTypeDeclarations(
        IndentingWriter writer,
        IReadOnlyCollection<(NamedType Type, ClassDeclaration Declaration)> instances)
    {
        foreach (var (type, declaration) in instances.Where(item =>
            RequiresClosedValueLayout(item.Type)).OrderBy(item =>
                item.Type.ConstructedIdentity!.CanonicalName, StringComparer.Ordinal))
        {
            ValidateClosedValueLayout(declaration);
            var field = declaration.MemberDeclarations.Declarations.OfType<FieldDeclaration>()
                .SingleOrDefault();
            writer.WriteLine($"struct {type.ConstructedIdentity!.CIdentifier} {{");
            writer.IncreaseIndent();
            writer.WriteLine($"{ToCStorageType(BuiltInSystemTypes.Object)} __base;");
            if (field is not null)
            {
                writer.WriteLine($"{type.TypeArguments[0].ToCIdentifier(false)} {field.Name};");
            }
            writer.DecreaseIndent();
            writer.WriteLine("};");
        }
    }

    private static bool IsReferenceFieldPropertyAccessor(
        PropertyDeclaration property,
        PropertyAccessorDeclaration accessor,
        IReadOnlyCollection<FieldDeclaration> fields)
    {
        if (accessor.Parameters.Count != 0 || property.Type is not GenericType propertyType)
        {
            return false;
        }
        FieldDeclaration? field = accessor.BodyFunction?.Body switch
        {
            [ReturnStatement
            {
                Expression: IdentifierExpression { TargetField: { } targetField },
            }] when accessor.Name == "get" => targetField.Declaration,
            [ExpressionStatement
            {
                Expression: AssignmentExpression
                {
                    Operator: "=",
                    Target: IdentifierExpression { TargetField: { } targetField },
                    Value: IdentifierExpression input,
                },
            }] when accessor.Name == "set" && input.Identifier.ToString() == "value" =>
                targetField.Declaration,
            _ => null,
        };
        return field is not null && fields.Contains(field) &&
            field.Type is GenericType fieldType && fieldType.Name == propertyType.Name;
    }

    private static bool IsReferenceFieldSetter(
        FunctionDeclaration function,
        IReadOnlyCollection<FieldDeclaration> fields) =>
        function.Parameters.Count == 1 && IsReferenceFieldAssignments(function, fields);

    private static bool IsReferenceFieldAssignments(
        FunctionDeclaration function,
        IReadOnlyCollection<FieldDeclaration> fields)
    {
        if (function.Parameters.Count == 0 ||
            function.Body is null || function.Body.Count != function.Parameters.Count)
        {
            return false;
        }
        var assignedFields = new HashSet<FieldDeclaration>();
        for (var index = 0; index < function.Parameters.Count; index++)
        {
            var parameter = function.Parameters[index];
            if (parameter.ParameterType is not GenericType parameterType ||
                function.Body[index] is not ExpressionStatement
                {
                    Expression: AssignmentExpression
                    {
                        Operator: "=",
                        Target: IdentifierExpression { TargetField: { } targetField },
                        Value: IdentifierExpression initialValue,
                    },
                } ||
                !fields.Contains(targetField.Declaration) ||
                !assignedFields.Add(targetField.Declaration) ||
                targetField.Declaration.Type is not GenericType fieldType ||
                fieldType.Name != parameterType.Name ||
                initialValue.Identifier.ToString() != parameter.Name)
            {
                return false;
            }
        }
        return true;
    }

    private static bool IsReferenceFieldGetter(
        FunctionDeclaration function,
        IReadOnlyCollection<FieldDeclaration> fields) =>
        function.Parameters.Count == 0 &&
        function.ReturnType is GenericType returnType &&
        function.Body is
        [ReturnStatement
        {
            Expression: IdentifierExpression { TargetField: { } targetField },
        }] &&
        fields.Contains(targetField.Declaration) &&
        targetField.Declaration.Type is GenericType fieldType &&
        fieldType.Name == returnType.Name;

    private static void WriteClosedGenericTypeInfos(
        IndentingWriter writer,
        IReadOnlyCollection<(NamedType Type, ClassDeclaration Declaration)> instances,
        string moduleName)
    {
        foreach (var (type, declaration) in instances.OrderBy(item =>
            item.Type.ConstructedIdentity!.CanonicalName, StringComparer.Ordinal))
        {
            ValidateClosedReferenceLayout(type, declaration);
            var identity = type.ConstructedIdentity!;
            var fields = declaration.MemberDeclarations.Declarations.OfType<FieldDeclaration>().ToArray();
            var closedFields = $"CX_ID_2({identity.CIdentifier}, __reflection_fields)";
            var arguments = declaration.GenericTypeNames
                .Zip(type.TypeArguments)
                .ToDictionary(pair => pair.First, pair => pair.Second);
            var functions = GetReflectionFunctions(declaration).ToArray();
            string? closedFunctions = null;
            if (functions.Length != 0)
            {
                closedFunctions = $"CX_ID_2({identity.CIdentifier}, __reflection_functions)";
                for (var index = 0; index < functions.Length; index++)
                {
                    if (functions[index].Parameters.Count == 0)
                    {
                        continue;
                    }
                    var closedParameters =
                        $"CX_ID_2({identity.CIdentifier}, __reflection_parameters_{index})";
                    writer.WriteLine();
                    writer.WriteLine($"static const struct cx_reflection_parameter {closedParameters}[] = {{");
                    writer.IncreaseIndent();
                    foreach (var parameter in functions[index].Parameters)
                    {
                        writer.WriteLine($"{{ 0, {ToTypeInfoPointer(GenericTypeSubstitution.Substitute(
                            parameter.ParameterType, arguments))}, " +
                            $"\"{parameter.Name}\", CX_NULL }},");
                    }
                    writer.DecreaseIndent();
                    writer.WriteLine("};");
                }
                writer.WriteLine($"static const struct cx_reflection_function {closedFunctions}[] = {{");
                writer.IncreaseIndent();
                for (var index = 0; index < functions.Length; index++)
                {
                    var function = functions[index];
                    var closedParameters = function.Parameters.Count == 0
                        ? "CX_NULL"
                        : $"CX_ID_2({identity.CIdentifier}, __reflection_parameters_{index})";
                    writer.WriteLine($"{{ {GetFunctionFlags(function)}, CX_REFLECTION_NO_SLOT, " +
                        $"{ToTypeInfoPointer(GenericTypeSubstitution.Substitute(function.ReturnType, arguments))}, " +
                        $"\"{function.Name}\", {closedParameters}, {function.Parameters.Count} }},");
                }
                writer.DecreaseIndent();
                writer.WriteLine("};");
            }
            if (fields.Length != 0)
            {
                writer.WriteLine();
                writer.WriteLine($"static const struct cx_reflection_field {closedFields}[] = {{");
                writer.IncreaseIndent();
                foreach (var field in fields)
                {
                    var fieldType = GenericTypeSubstitution.Substitute(field.Type, arguments);
                    writer.WriteLine(
                        $"{{ {GetMemberFlags(field.MemberModifiers)}, " +
                        $"(cx_uint)offsetof({(RequiresClosedValueLayout(type)
                            ? $"struct {identity.CIdentifier}"
                            : declaration.ToCIdentifier(moduleName))}, {field.Name}), " +
                        $"{ToTypeInfoPointer(fieldType)}, \"{field.Name}\" }},");
                }
                writer.DecreaseIndent();
                writer.WriteLine("};");
            }
            writer.WriteLine();
            writer.WriteLine($"CX_BEGIN_VTABLE_DEF({identity.CIdentifier})");
            writer.WriteLine("CX_END_VTABLE_DEF;");
            writer.WriteLine($"struct CX_ID_4(cxcore, System, Reflection, TypeInfo) " +
                $"CX_TYPEINFO_NAME({identity.CIdentifier}) = {{");
            writer.IncreaseIndent();
            writer.WriteLine($".Hash = 0x{identity.RuntimeHash:X}ULL,");
            writer.WriteLine($".Flags = {string.Join(" | ", GetTypeInfoFlags(declaration))},");
            writer.WriteLine($".Size = sizeof({(RequiresClosedValueLayout(type)
                ? $"struct {identity.CIdentifier}"
                : declaration.ToCIdentifier(moduleName))}),");
            writer.WriteLine($".Name = &{new QualifiedIdentifier("__name", declaration.FullName).ToCIdentifier()},");
            writer.WriteLine($".Namespace = &{new QualifiedIdentifier("__namespace", declaration.Namespace).ToCIdentifier()},");
            writer.WriteLine(".BaseType = { ._obj = &CX_ID_4(cxcore, System, Object, __typeinfo) },");
            if (fields.Length != 0)
            {
                writer.WriteLine($".RuntimeFields = (cx_ptr){closedFields},");
                writer.WriteLine($".RuntimeFieldCount = {fields.Length},");
            }
            if (GetReflectionFunctionCount(declaration) != 0)
            {
                writer.WriteLine($".RuntimeFunctions = (cx_ptr)" +
                    $"{closedFunctions ?? GetReflectionFunctionsIdentifier(declaration, moduleName).ToCIdentifier()},");
                writer.WriteLine($".RuntimeFunctionCount = {GetReflectionFunctionCount(declaration)},");
            }
            writer.WriteLine($".GenericArity = {declaration.GenericTypeNames.Length},");
            writer.DecreaseIndent();
            writer.WriteLine("};");
        }
    }

    private static void WriteEnumTypeInfoDefinition(
        IndentingWriter writer,
        EnumDeclaration declaration,
        string moduleName)
    {
        var nameIdentifier = new QualifiedIdentifier("__name", declaration.FullName).ToCIdentifier();
        var namespaceIdentifier = new QualifiedIdentifier("__namespace", declaration.Namespace).ToCIdentifier();
        var enumName = declaration.ToCIdentifier(moduleName);
        var visibility = declaration.Visibility switch
        {
            Visibility.Public => "CX_REFLECTION_FLAG_VISIBILITY_PUBLIC",
            Visibility.Protected => "CX_REFLECTION_FLAG_VISIBILITY_PROTECTED",
            Visibility.Internal => "CX_REFLECTION_FLAG_VISIBILITY_INTERNAL",
            Visibility.Private => "CX_REFLECTION_FLAG_VISIBILITY_PRIVATE",
            _ => "CX_REFLECTION_FLAG_VISIBILITY_HIDDEN",
        };
        writer.WriteLine($"struct CX_ID_4(cxcore, System, Reflection, TypeInfo) {new QualifiedIdentifier(moduleName, declaration.FullName, "__typeinfo").ToCIdentifier()} = {{");
        writer.IncreaseIndent();
        writer.WriteLine($".Hash = 0x{GetTypeNameHash(declaration.FullName, moduleName):X},");
        writer.WriteLine($".Flags = {visibility} | CX_REFLECTION_FLAG_TYPE_ENUM,");
        writer.WriteLine($".Size = sizeof({enumName}),");
        writer.WriteLine($".Name = &{nameIdentifier},");
        writer.WriteLine($".Namespace = &{namespaceIdentifier},");
        writer.WriteLine(".BaseType = { ._obj = CX_NULL },");
        writer.DecreaseIndent();
        writer.WriteLine("};");
    }

    private static void WriteTypeInfoDefinition(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        string moduleName)
    {
        var nameIdentifier = new QualifiedIdentifier("__name", classDeclaration.FullName);
        var namespaceIdentifier = new QualifiedIdentifier("__namespace", classDeclaration.Namespace);

        string[] flags = GetTypeInfoFlags(classDeclaration).ToArray();
        if (flags.Length == 0)
        {
            flags = ["0"];
        }
        string flagsString = string.Join(" | ", flags);

        var reflectedInterfaces = GetReflectedInterfaces(classDeclaration).ToArray();
        var fields = classDeclaration.MemberDeclarations.Declarations.OfType<FieldDeclaration>().ToArray();
        var functionCount = GetReflectionFunctionCount(classDeclaration);
        var baseType = classDeclaration.ClassType == ClassType.Class && !classDeclaration.IsStatic &&
            !(moduleName == "cxcore" && classDeclaration.Name == "Object")
            ? classDeclaration.BaseClassType switch
            {
                NamedType namedType => $"&{new QualifiedIdentifier(namedType.ResolvedTypeFullName, "__typeinfo").ToCIdentifier()}",
                _ => "&CX_ID_4(cxcore, System, Object, __typeinfo)",
            }
            : "CX_NULL";
        var size = classDeclaration.IsStatic || classDeclaration.ClassType == ClassType.Interface
            ? "0"
            : $"sizeof({classDeclaration.ToCIdentifier(moduleName)})";
        var interfaceMap = reflectedInterfaces.Length == 0
            ? "CX_NULL"
            : $"(cx_ptr){GetInterfaceRuntimeMapIdentifier(classDeclaration, moduleName).ToCIdentifier()}";
        var fieldMap = fields.Length == 0
            ? "CX_NULL"
            : $"(cx_ptr){GetReflectionFieldsIdentifier(classDeclaration, moduleName).ToCIdentifier()}";
        var functionMap = functionCount == 0
            ? "CX_NULL"
            : $"(cx_ptr){GetReflectionFunctionsIdentifier(classDeclaration, moduleName).ToCIdentifier()}";

        writer.WriteLine($"struct CX_ID_4(cxcore, System, Reflection, TypeInfo) {new QualifiedIdentifier(moduleName, classDeclaration.FullName, "__typeinfo").ToCIdentifier()} = {{");
        writer.IncreaseIndent();
        writer.WriteLine($".Hash = 0x{GetTypeNameHash(classDeclaration.FullName, moduleName, classDeclaration.GenericTypeNames.Length):X},");
        writer.WriteLine($".Flags = {flagsString},");
        writer.WriteLine($".Size = {size},");
        writer.WriteLine($".Name = &{nameIdentifier.ToCIdentifier()},");
        writer.WriteLine($".Namespace = &{namespaceIdentifier.ToCIdentifier()},");
        writer.WriteLine($".BaseType = {{ ._obj = {baseType} }},");
        writer.WriteLine($".RuntimeInterfaces = {interfaceMap},");
        writer.WriteLine($".RuntimeInterfaceCount = {reflectedInterfaces.Length},");
        writer.WriteLine($".RuntimeFields = {fieldMap},");
        writer.WriteLine($".RuntimeFieldCount = {fields.Length},");
        writer.WriteLine($".RuntimeFunctions = {functionMap},");
        writer.WriteLine($".RuntimeFunctionCount = {functionCount},");
        writer.WriteLine($".GenericArity = {classDeclaration.GenericTypeNames.Length},");
        writer.DecreaseIndent();
        writer.WriteLine("};");
    }

    private static IEnumerable<string> GetTypeInfoFlags(ClassDeclaration classDeclaration)
    {
        if (classDeclaration.IsStatic)
        {
            yield return "CX_REFLECTION_FLAG_STATIC";
        }
        if (classDeclaration.IsAbstract)
        {
            yield return "CX_REFLECTION_FLAG_ABSTRACT";
        }
        if (classDeclaration.IsFinal)
        {
            yield return "CX_REFLECTION_FLAG_FINAL";
        }
        if (classDeclaration.GenericTypeNames.Length > 0)
        {
            yield return "CX_REFLECTION_FLAG_GENERIC";
            yield return "CX_REFLECTION_FLAG_TYPE_GENERIC";
        }

        if (classDeclaration.Visibility == Visibility.Public)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_PUBLIC";
        }
        else if (classDeclaration.Visibility == Visibility.Protected)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_PROTECTED";
        }
        else if (classDeclaration.Visibility == Visibility.Internal)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_INTERNAL";
        }
        else if (classDeclaration.Visibility == Visibility.Private)
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_PRIVATE";
        }
        else
        {
            yield return "CX_REFLECTION_FLAG_VISIBILITY_HIDDEN";
        }

        yield return classDeclaration.ClassType switch
        {
            ClassType.Class => "CX_REFLECTION_FLAG_TYPE_CLASS",
            ClassType.Struct => "CX_REFLECTION_FLAG_TYPE_STRUCT",
            ClassType.Interface => "CX_REFLECTION_FLAG_TYPE_INTERFACE",
            _ => throw new InternalCompilerException($"Unsupported class type: {classDeclaration.ClassType}")
        };
    }

    private static void WriteVTableDefinition(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        string moduleName)
    {
        writer.WriteLine($"CX_BEGIN_VTABLE_DEF({classDeclaration.ToCIdentifier(moduleName, false)})");

        foreach (var slot in classDeclaration.VirtualMethodSlots.OrderBy(slot => slot.Index))
        {
            if (slot.Implementation is null)
            {
                writer.WriteLine("{ .function = (cx_vtable_function)0 },");
            }
            else
            {
                writer.WriteLine($"CX_VTABLE_ENTRY({ToCFunctionName(slot.Implementation, moduleName)})");
            }
        }

        writer.WriteLine("CX_END_VTABLE_DEF;");
    }

    private static void WriteInterfaceVTableDefinition(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        InterfaceDispatchTable table,
        string moduleName)
    {
        var vtableName = GetInterfaceVTableIdentifier(
            classDeclaration,
            table.Interface,
            moduleName).ToCIdentifier();
        writer.WriteLine(
            $"CX_BEGIN_INTERFACE_VTABLE_DEF({vtableName}, " +
            $"{classDeclaration.ToCIdentifier(moduleName, false)})");
        foreach (var slot in table.Slots.OrderBy(slot => slot.Index))
        {
            writer.WriteLine(slot.Implementation is null
                ? "{ .function = (cx_vtable_function)0 },"
                : $"CX_VTABLE_ENTRY({GetInterfaceThunkIdentifier(classDeclaration, table.Interface, slot.Index, moduleName).ToCIdentifier()})");
        }
        foreach (var targetInterface in table.Interface.InterfaceUpcastTargets)
        {
            var targetVTable = GetInterfaceVTableIdentifier(
                classDeclaration,
                targetInterface,
                moduleName).ToCIdentifier();
            writer.WriteLine($"{{ .data = {targetVTable} }},");
        }
        writer.WriteLine("CX_END_VTABLE_DEF;");
    }

    private static void WriteInterfaceRuntimeMap(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        string moduleName)
    {
        var interfaces = GetReflectedInterfaces(classDeclaration).ToArray();
        if (interfaces.Length == 0)
        {
            return;
        }

        writer.WriteLine($"static const struct cx_interface_impl {GetInterfaceRuntimeMapIdentifier(classDeclaration, moduleName).ToCIdentifier()}[] = {{");
        writer.IncreaseIndent();
        foreach (var @interface in interfaces)
        {
            var interfaceTypeInfo = new QualifiedIdentifier(
                moduleName,
                @interface.FullName,
                "__typeinfo").ToCIdentifier();
            var vtable = classDeclaration.ClassType == ClassType.Class
                ? GetInterfaceVTableIdentifier(classDeclaration, @interface, moduleName).ToCIdentifier()
                : "CX_NULL";
            writer.WriteLine($"{{ &{interfaceTypeInfo}, {vtable} }},");
        }
        writer.DecreaseIndent();
        writer.WriteLine("};");
    }

    private static IEnumerable<ClassDeclaration> GetReflectedInterfaces(ClassDeclaration declaration)
    {
        return declaration.ClassType == ClassType.Interface
            ? declaration.InterfaceUpcastTargets
            : declaration.InterfaceDispatchTables.Select(table => table.Interface);
    }

    private static void WriteReflectionMetadata(
        IndentingWriter writer,
        ClassDeclaration declaration,
        string moduleName)
    {
        var fields = declaration.MemberDeclarations.Declarations.OfType<FieldDeclaration>().ToArray();
        if (fields.Length > 0)
        {
            writer.WriteLine($"static const struct cx_reflection_field {GetReflectionFieldsIdentifier(declaration, moduleName).ToCIdentifier()}[] = {{");
            writer.IncreaseIndent();
            foreach (var field in fields)
            {
                var offset = field.IsStatic
                    ? "CX_REFLECTION_NO_OFFSET"
                    : $"(cx_uint)offsetof({declaration.ToCIdentifier(moduleName)}, {field.Name})";
                writer.WriteLine(
                    $"{{ {GetMemberFlags(field.MemberModifiers)}, {offset}, " +
                    $"{ToTypeInfoPointer(field.Type)}, \"{field.Name}\" }},");
            }
            writer.DecreaseIndent();
            writer.WriteLine("};");
        }

        var functions = GetReflectionFunctions(declaration).ToArray();
        for (var index = 0; index < functions.Length; index++)
        {
            var function = functions[index];
            if (function.Parameters.Count == 0)
            {
                continue;
            }
            writer.WriteLine($"static const struct cx_reflection_parameter {GetReflectionParametersIdentifier(declaration, moduleName, index).ToCIdentifier()}[] = {{");
            writer.IncreaseIndent();
            foreach (var parameter in function.Parameters)
            {
                writer.WriteLine(
                    $"{{ 0, {ToTypeInfoPointer(parameter.ParameterType)}, " +
                    $"\"{parameter.Name}\", CX_NULL }},");
            }
            writer.DecreaseIndent();
            writer.WriteLine("};");
        }

        if (functions.Length == 0)
        {
            return;
        }
        writer.WriteLine($"static const struct cx_reflection_function {GetReflectionFunctionsIdentifier(declaration, moduleName).ToCIdentifier()}[] = {{");
        writer.IncreaseIndent();
        for (var index = 0; index < functions.Length; index++)
        {
            var function = functions[index];
            var parameters = function.Parameters.Count == 0
                ? "CX_NULL"
                : GetReflectionParametersIdentifier(declaration, moduleName, index).ToCIdentifier();
            var slot = function.VirtualSlotIndex is { } virtualSlot
                ? virtualSlot.ToString()
                : "CX_REFLECTION_NO_SLOT";
            writer.WriteLine(
                $"{{ {GetFunctionFlags(function)}, {slot}, " +
                $"{ToTypeInfoPointer(function.ReturnType)}, \"{function.Name}\", " +
                $"{parameters}, {function.Parameters.Count} }},");
        }
        writer.DecreaseIndent();
        writer.WriteLine("};");
    }

    private static IEnumerable<ReflectionFunctionSource> GetReflectionFunctions(
        ClassDeclaration declaration)
    {
        foreach (var function in declaration.MemberDeclarations.Declarations.OfType<FunctionDeclaration>())
        {
            yield return new ReflectionFunctionSource(
                function is ConstructorDeclaration ? declaration.Name : function.Name,
                function.ReturnType,
                function.Parameters,
                function.MemberModifiers,
                function.Const,
                function is ConstructorDeclaration,
                null,
                function.VirtualSlotIndex);
        }
        foreach (var property in declaration.MemberDeclarations.Declarations.OfType<PropertyDeclaration>())
        {
            foreach (var accessor in property.PropertyAccessorDeclarations)
            {
                var parameters = accessor.Parameters.ToList();
                if (accessor.Name == "set")
                {
                    parameters.Add(new FunctionParameter("value", property.Type, null));
                }
                yield return new ReflectionFunctionSource(
                    property.Name,
                    accessor.Name == "set" ? BuiltInSystemTypes.Void : property.Type,
                    parameters,
                    property.MemberModifiers,
                    accessor.Const,
                    false,
                    accessor.Name,
                    accessor.BodyFunction?.VirtualSlotIndex,
                    accessor.Extern);
            }
        }
    }

    private static int GetReflectionFunctionCount(ClassDeclaration declaration)
    {
        return GetReflectionFunctions(declaration).Count();
    }

    private static QualifiedIdentifier GetReflectionFieldsIdentifier(
        ClassDeclaration declaration,
        string moduleName) =>
        new(moduleName, declaration.FullName, "__reflection_fields");

    private static QualifiedIdentifier GetReflectionFunctionsIdentifier(
        ClassDeclaration declaration,
        string moduleName) =>
        new(moduleName, declaration.FullName, "__reflection_functions");

    private static QualifiedIdentifier GetReflectionParametersIdentifier(
        ClassDeclaration declaration,
        string moduleName,
        int index) =>
        new(moduleName, declaration.FullName, $"__reflection_params_{index}");

    private static string ToTypeInfoPointer(TypeBase type)
    {
        type = type is ConstType constType ? constType.UnderlyingType : type;
        if (type is PtrType or FunctionType or AutoType or GenericType or NullType)
        {
            return "CX_NULL";
        }
        return $"&{GetTypeInfoIdentifier(type).ToCIdentifier()}";
    }

    private static string GetMemberFlags(IEnumerable<MemberModifier> modifiers)
    {
        var modifierSet = modifiers.ToHashSet();
        var flags = new List<string>();
        if (modifierSet.Contains(MemberModifier.Public)) flags.Add("CX_REFLECTION_FLAG_VISIBILITY_PUBLIC");
        else if (modifierSet.Contains(MemberModifier.Protected)) flags.Add("CX_REFLECTION_FLAG_VISIBILITY_PROTECTED");
        else if (modifierSet.Contains(MemberModifier.Internal)) flags.Add("CX_REFLECTION_FLAG_VISIBILITY_INTERNAL");
        else if (modifierSet.Contains(MemberModifier.Private)) flags.Add("CX_REFLECTION_FLAG_VISIBILITY_PRIVATE");
        else flags.Add("CX_REFLECTION_FLAG_VISIBILITY_HIDDEN");
        if (modifierSet.Contains(MemberModifier.Static)) flags.Add("CX_REFLECTION_FLAG_STATIC");
        if (modifierSet.Contains(MemberModifier.Virtual) || modifierSet.Contains(MemberModifier.Override)) flags.Add("CX_REFLECTION_FLAG_VIRTUAL");
        if (modifierSet.Contains(MemberModifier.Abstract)) flags.Add("CX_REFLECTION_FLAG_ABSTRACT");
        if (modifierSet.Contains(MemberModifier.Final)) flags.Add("CX_REFLECTION_FLAG_FINAL");
        if (modifierSet.Contains(MemberModifier.Extern)) flags.Add("CX_REFLECTION_FLAG_EXTERN");
        return string.Join(" | ", flags);
    }

    private static string GetFunctionFlags(ReflectionFunctionSource function)
    {
        var flags = new List<string> { GetMemberFlags(function.Modifiers) };
        if (function.Const) flags.Add("CX_REFLECTION_FLAG_CONST_CALL");
        if (function.Extern) flags.Add("CX_REFLECTION_FLAG_EXTERN");
        if (function.IsConstructor) flags.Add("CX_REFLECTION_FLAG_FUNCTION_CONSTRUCTOR");
        if (function.AccessorKind == "get") flags.Add("CX_REFLECTION_FLAG_FUNCTION_PROPERTY_GET");
        if (function.AccessorKind == "set") flags.Add("CX_REFLECTION_FLAG_FUNCTION_PROPERTY_SET");
        return string.Join(" | ", flags.Distinct());
    }

    private sealed record ReflectionFunctionSource(
        string Name,
        TypeBase ReturnType,
        IReadOnlyList<FunctionParameter> Parameters,
        MemberModifier[] Modifiers,
        bool Const,
        bool IsConstructor,
        string? AccessorKind,
        int? VirtualSlotIndex,
        bool Extern = false);

    private static QualifiedIdentifier GetInterfaceRuntimeMapIdentifier(
        ClassDeclaration classDeclaration,
        string moduleName)
    {
        return new QualifiedIdentifier(moduleName, classDeclaration.FullName, "__interfaces");
    }

    private static void WriteInterfaceDispatchThunks(
        IndentingWriter writer,
        IEnumerable<DeclarationBase> declarations,
        string moduleName)
    {
        foreach (var classDeclaration in EnumerateClasses(declarations)
            .Where(type => type.ClassType == ClassType.Class))
        {
            foreach (var table in classDeclaration.InterfaceDispatchTables)
            {
                var vtableName = GetInterfaceVTableIdentifier(
                    classDeclaration,
                    table.Interface,
                    moduleName).ToCIdentifier();
                writer.WriteLine($"extern union cx_vtable_entry {vtableName}[];");
            }
        }
        writer.WriteLine();

        foreach (var classDeclaration in EnumerateClasses(declarations)
            .Where(type => type.ClassType == ClassType.Class))
        {
            foreach (var table in classDeclaration.InterfaceDispatchTables)
            {
                foreach (var slot in table.Slots.Where(slot => slot.Implementation is not null))
                {
                    WriteInterfaceDispatchThunk(
                        writer,
                        classDeclaration,
                        table.Interface,
                        slot,
                        moduleName);
                }
            }
        }
    }

    private static void WriteInterfaceDispatchThunk(
        IndentingWriter writer,
        ClassDeclaration classDeclaration,
        ClassDeclaration interfaceDeclaration,
        InterfaceDispatchSlot slot,
        string moduleName)
    {
        var thunkName = GetInterfaceThunkIdentifier(
            classDeclaration,
            interfaceDeclaration,
            slot.Index,
            moduleName).ToCIdentifier();
        var parameters = new[] { "cx_ptr __root" }.Concat(slot.Parameters.Select(
            parameter => $"{parameter.ParameterType.ToCIdentifier(false)} {parameter.Name}"));
        writer.WriteLine(
            $"static {slot.ReturnType.ToCReturnType(false)} {thunkName}(" +
            $"{string.Join(", ", parameters)}) {{");
        writer.IncreaseIndent();

        var argumentNames = slot.Parameters.Select(parameter => parameter.Name).ToArray();
        string call;
        if (slot.ImplementationFunction is { } implementation &&
            implementation.VirtualSlotIndex is { } virtualSlotIndex)
        {
            var virtualContract = implementation.VirtualContract ?? implementation;
            var receiverConst = virtualContract.Const ? "const " : string.Empty;
            var receiverType =
                $"{receiverConst}{virtualContract.ParentClassDeclaration!.ToCIdentifier(moduleName)}*";
            var parameterTypes = new[] { receiverType }.Concat(
                virtualContract.Parameters.Select(parameter =>
                    parameter.ParameterType.ToCIdentifier(false)));
            var functionPointer =
                $"({virtualContract.ReturnType.ToCReturnType(false)} (*)({string.Join(", ", parameterTypes)}))";
            var receiver = $"({receiverType})__root";
            call = $"({functionPointer}((union cx_vtable_entry*)CX_GET_VTABLE({receiver}))[{virtualSlotIndex}].function)" +
                $"({string.Join(", ", new[] { receiver }.Concat(argumentNames))})";
        }
        else if (slot.ImplementationFunction is { } directImplementation)
        {
            var receiverConst = directImplementation.Const ? "const " : string.Empty;
            var receiver =
                $"({receiverConst}{directImplementation.ParentClassDeclaration!.ToCIdentifier(moduleName)}*)__root";
            call = $"{ToCFunctionName(directImplementation, moduleName)}(" +
                $"{string.Join(", ", new[] { receiver }.Concat(argumentNames))})";
        }
        else
        {
            var accessor = slot.ImplementationAccessor!;
            var property = accessor.ParentPropertyDeclaration;
            var receiverConst = accessor.Const ? "const " : string.Empty;
            var receiver =
                $"({receiverConst}{property.ParentClassDeclaration.ToCIdentifier(moduleName)}*)__root";
            call = $"{ToCPropertyAccessorName(accessor, moduleName)}(" +
                $"{string.Join(", ", new[] { receiver }.Concat(argumentNames))})";
        }

        writer.WriteLine(slot.ReturnType is VoidType ? $"{call};" : $"return {call};");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static QualifiedIdentifier GetInterfaceVTableIdentifier(
        ClassDeclaration classDeclaration,
        ClassDeclaration interfaceDeclaration,
        string moduleName)
    {
        return GetInterfaceVTableIdentifier(
            new QualifiedIdentifier(moduleName, classDeclaration.FullName),
            new QualifiedIdentifier(moduleName, interfaceDeclaration.FullName));
    }

    private static QualifiedIdentifier GetInterfaceVTableIdentifier(
        QualifiedIdentifier className,
        QualifiedIdentifier interfaceName)
    {
        var interfaceParts = className.Parts.FirstOrDefault() == interfaceName.Parts.FirstOrDefault()
            ? interfaceName.Parts.Skip(1).ToArray()
            : interfaceName.Parts;
        return new QualifiedIdentifier(
            className,
            new QualifiedIdentifier("__iface"),
            new QualifiedIdentifier(interfaceParts),
            new QualifiedIdentifier("__vtable"));
    }

    private static QualifiedIdentifier GetInterfaceThunkIdentifier(
        ClassDeclaration classDeclaration,
        ClassDeclaration interfaceDeclaration,
        int slotIndex,
        string moduleName)
    {
        var vtableName = GetInterfaceVTableIdentifier(
            classDeclaration,
            interfaceDeclaration,
            moduleName);
        return new QualifiedIdentifier(vtableName, $"slot_{slotIndex}");
    }

    private static IEnumerable<ClassDeclaration> EnumerateClasses(
        IEnumerable<DeclarationBase> declarations)
    {
        foreach (var classDeclaration in declarations.OfType<ClassDeclaration>())
        {
            yield return classDeclaration;
            foreach (var nested in EnumerateClasses(
                classDeclaration.MemberDeclarations.Declarations))
            {
                yield return nested;
            }
        }
    }

    private static IEnumerable<EnumDeclaration> EnumerateEnums(
        IEnumerable<DeclarationBase> declarations)
    {
        foreach (var declaration in declarations)
        {
            if (declaration is EnumDeclaration enumDeclaration)
            {
                yield return enumDeclaration;
            }
            else if (declaration is ClassDeclaration classDeclaration)
            {
                foreach (var nested in EnumerateEnums(classDeclaration.MemberDeclarations.Declarations))
                {
                    yield return nested;
                }
            }
        }
    }

    private static List<DeclarationBase> GetDeclarations(CxProject project)
    {
        List<DeclarationBase> declarations = [];

        foreach (var compilationContext in project.CompilationContexts)
        {
            foreach (var declaration in compilationContext.DeclarationScope.Declarations)
            {
                if (declaration is ClassDeclaration classDeclaration)
                {
                    declarations.Add(classDeclaration);
                }
                else if (declaration is FunctionDeclaration functionDeclaration)
                {
                    declarations.Add(functionDeclaration);
                }
                else if (declaration is EnumDeclaration enumDeclaration)
                {
                    declarations.Add(enumDeclaration);
                }
                else
                {
                    throw new InternalCompilerException(
                        $"Unsupported declaration type: {declaration.GetType().Name} in project '{project.Name}'");
                }
            }
        }

        var cxcoreTypeOrder = new Dictionary<string, int>
        {
            { "Object", -1000 },
            { "Nullable", -900 },
            { "TypeInfo", -800 },
            { "VersionInfo", -700 }
        }; // TODO: Remove this hack for cxcore

        var result = declarations.Order(Comparer<DeclarationBase>.Create((x, y) =>
        {
            if (x is ClassDeclaration xClassDeclaration && y is ClassDeclaration yClassDeclaration)
            {
                var depthComparison = GetInheritanceDepth(xClassDeclaration)
                    .CompareTo(GetInheritanceDepth(yClassDeclaration));
                if (depthComparison != 0)
                {
                    return depthComparison;
                }
                if (project.Name == "cxcore") // TODO: Remove this hack for cxcore
                {
                    if (cxcoreTypeOrder.ContainsKey(x.Name) && !cxcoreTypeOrder.ContainsKey(y.Name))
                    {
                        return -1;
                    }
                    else if (!cxcoreTypeOrder.ContainsKey(x.Name) && cxcoreTypeOrder.ContainsKey(y.Name))
                    {
                        return 1;
                    }
                    else if (cxcoreTypeOrder.ContainsKey(x.Name) && cxcoreTypeOrder.ContainsKey(y.Name))
                    {
                        return cxcoreTypeOrder[x.Name].CompareTo(cxcoreTypeOrder[y.Name]);
                    }
                }

                if (ReferenceEquals(xClassDeclaration.BaseClassDeclaration, yClassDeclaration))
                {
                    return 1;
                }
                else if (ReferenceEquals(yClassDeclaration.BaseClassDeclaration, xClassDeclaration))
                {
                    return -1;
                }
                else
                {
                    return QualifiedIdentifier.Compare(xClassDeclaration.FullName, yClassDeclaration.FullName);
                }
            }
            else if (x.GetType() == y.GetType())
            {
                return QualifiedIdentifier.Compare(x.FullName, y.FullName);
            }
            return GetDeclarationOrder(x).CompareTo(GetDeclarationOrder(y));
        })).ToList();
        return result;

        static int GetDeclarationOrder(DeclarationBase declaration) => declaration switch
        {
            EnumDeclaration => 0,
            ClassDeclaration => 1,
            FunctionDeclaration => 2,
            _ => 3,
        };

        static int GetInheritanceDepth(ClassDeclaration declaration)
        {
            var depth = 0;
            while (declaration.BaseClassDeclaration is { } baseClass)
            {
                depth++;
                declaration = baseClass;
            }
            return depth;
        }
    }

    private static int GetNameOverrideIndex(FunctionDeclaration functionDeclaration, IReadOnlyCollection<DeclarationBase> declarations)
    {
        var nameOverrides = declarations
            .OfType<FunctionDeclaration>()
            .Where(fd => fd.FullName == functionDeclaration.FullName)
            .ToList();
        return nameOverrides.IndexOf(functionDeclaration) + 1;
    }

    private static string ToCIdentifier(this ClassDeclaration classDeclaration, string moduleName, bool includeStruct = true)
    {
        var fullName = new QualifiedIdentifier(moduleName, classDeclaration.FullName);
        return $"{(includeStruct ? "struct " : "")}{fullName.ToCIdentifier()}";
    }

    private static string ToCIdentifier(this EnumDeclaration enumDeclaration, string moduleName)
    {
        return new QualifiedIdentifier(moduleName, enumDeclaration.FullName).ToCIdentifier();
    }

    private static string ToCIdentifier(this EnumMemberDeclaration member, string moduleName)
    {
        return new QualifiedIdentifier(moduleName, member.FullName).ToCIdentifier();
    }

    private static string ToCStorageType(TypeBase type)
    {
        type = type is ConstType constType ? constType.UnderlyingType : type;
        return type switch
        {
            ObjectType => "struct CX_ID_3(cxcore, System, Object)",
            NamedType { ClassType: ClassType.Class } namedType =>
                $"struct {namedType.ResolvedTypeFullName.ToCIdentifier()}",
            _ => type.ToCIdentifier(false).TrimEnd('*', ' '),
        };
    }

    private static string ToCIdentifier(this FunctionDeclaration functionDeclaration, string moduleName, int nameOverrideIndex)
    {
        var name = nameOverrideIndex > 1
            ? new QualifiedIdentifier(functionDeclaration.FullName, $"_{nameOverrideIndex}")
            : functionDeclaration.FullName;
        var fullName = new QualifiedIdentifier(moduleName, name);
        var returnType = ReturnsGenericClassReference(functionDeclaration)
            ? "void*"
            : functionDeclaration.ReturnType.ToCReturnType(@const: false);
        return $"{returnType} {fullName.ToCIdentifier()}";
    }

    private static bool ReturnsGenericClassReference(FunctionDeclaration function) =>
        function.ParentClassDeclaration is { GenericTypeNames.Length: > 0 } &&
        function.ReturnType is GenericType;

    private static string ToCFunctionName(
        FunctionDeclaration functionDeclaration,
        string moduleName)
    {
        var declarations = functionDeclaration.ParentClassDeclaration is null
            ? Array.Empty<DeclarationBase>()
            : functionDeclaration.ParentClassDeclaration.MemberDeclarations.Declarations.ToArray();
        var nameOverrideIndex = GetNameOverrideIndex(functionDeclaration, declarations);
        var name = nameOverrideIndex > 1
            ? new QualifiedIdentifier(functionDeclaration.FullName, $"_{nameOverrideIndex}")
            : functionDeclaration.FullName;
        return new QualifiedIdentifier(moduleName, name).ToCIdentifier();
    }

    private static string ToCIdentifier(this PropertyAccessorDeclaration propertyAccessorDeclaration, string moduleName)
    {
        var returnType = propertyAccessorDeclaration.Name == "set"
            ? BuiltInSystemTypes.Void
            : propertyAccessorDeclaration.ParentPropertyDeclaration.Type;
        var cReturnType = ReturnsGenericClassPropertyReference(propertyAccessorDeclaration)
            ? "void*"
            : returnType.ToCReturnType(false);
        return $"{cReturnType} {ToCPropertyAccessorName(propertyAccessorDeclaration, moduleName)}";
    }

    private static bool ReturnsGenericClassPropertyReference(PropertyAccessorDeclaration accessor) =>
        accessor.Name == "get" &&
        accessor.BodyFunction is not null && accessor.Parameters.Count == 0 &&
        accessor.ParentPropertyDeclaration.ParentClassDeclaration.GenericTypeNames.Length > 0 &&
        accessor.ParentPropertyDeclaration.Type is GenericType;

    private static string ToCPropertyAccessorName(
        PropertyAccessorDeclaration propertyAccessorDeclaration,
        string moduleName)
    {
        var accessorName = $"__{(propertyAccessorDeclaration.Const ? "const_" : "")}{propertyAccessorDeclaration.Name}";
        var name = new QualifiedIdentifier(
            propertyAccessorDeclaration.ParentPropertyDeclaration.FullName,
            accessorName);
        return new QualifiedIdentifier(moduleName, name).ToCIdentifier();
    }

    private static string ToCIdentifier(this TypeBase typeBase, bool @const)
    {
        var constString = @const ? "const " : "";
        return typeBase switch
        {
            ConstType constType => constType.UnderlyingType.ToCIdentifier(true),
            BoolType => "cx_bool",
            CharType => "cx_char",

            SByteType => "cx_sbyte",
            ShortType => "cx_short",
            IntType => "cx_int",
            LongType => "cx_long",

            ByteType => "cx_byte",
            UShortType => "cx_ushort",
            UIntType => "cx_uint",
            ULongType => "cx_ulong",

            FloatType => "cx_float",
            DoubleType => "cx_double",

            ObjectType => $"{constString}struct CX_ID_3(cxcore, System, Object)*",
            StringType => $"{constString}struct CX_ID_3(cxcore, System, String)*",
            PtrType => $"{constString}cx_ptr",

            FunctionType => throw new NotImplementedException(), // TODO
            VoidType => "void",
            NullType => "cx_ptr",

            ArrayType => $"{constString}struct CX_ID_3(cxcore, System, Array)*",
            NullableType => $"{constString}struct CX_ID_3(cxcore, System, Nullable)",

            NamedType namedType when namedType.ClassType == ClassType.Struct => $"{constString}struct {namedType.ResolvedTypeFullName.ToCIdentifier()}",
            NamedType namedType when namedType.ClassType == ClassType.Class &&
                RequiresClosedValueLayout(namedType) =>
                $"{constString}struct {namedType.ConstructedIdentity!.CIdentifier}*",
            NamedType namedType when namedType.ClassType == ClassType.Class => $"{constString}struct {namedType.ResolvedTypeFullName.ToCIdentifier()}*",
            NamedType { ClassType: ClassType.Interface } => $"{constString}struct cx_iface_ref",
            NamedType namedType when namedType.ClassType == ClassType.Enum => $"{constString}{namedType.ResolvedTypeFullName.ToCIdentifier()}",

            _ => "_unknowntype_" // TODO: throw below exception for unsupported types
            //_ => throw new InternalCompilerException($"Unsupported type: {typeBase.GetType().Name}"),
        };
    }

    private static string ToCIdentifier(this QualifiedIdentifier qualifiedIdentifier)
    {
        if (qualifiedIdentifier.IsEmpty)
        {
            throw new InternalCompilerException("QualifiedIdentifier cannot be empty");
        }

        if (qualifiedIdentifier.Parts.Length == 1)
        {
            return qualifiedIdentifier.Parts[0];
        }

        return $"CX_ID_{qualifiedIdentifier.Parts.Length}({string.Join(", ", qualifiedIdentifier.Parts)})";
    }

    private static string ToCReturnType(this TypeBase typeBase, bool @const)
    {
        if (IsGenericValueType(typeBase))
        {
            return "void";
        }

        return typeBase.ToCIdentifier(@const);
    }

    private static string ToCParameterType(TypeBase typeBase)
    {
        return IsGenericValueType(typeBase)
            ? "void*"
            : typeBase.ToCIdentifier(@const: false);
    }

    private static bool IsGenericValueType(TypeBase typeBase)
    {
        var effectiveType = typeBase is ConstType constType
            ? constType.UnderlyingType
            : typeBase;
        return effectiveType is GenericType ||
            effectiveType is NamedType
            {
                ClassType: ClassType.Struct,
                GenericParams.Length: > 0,
            };
    }

    private static ulong GetTypeNameHash(
        QualifiedIdentifier typeName,
        string moduleName,
        int genericArity = 0)
    {
        var fullName = new QualifiedIdentifier(moduleName, typeName);
        var fullNameString = $"{fullName}{(genericArity == 0 ? string.Empty : $"`{genericArity}")}";
        byte[] bytes = Encoding.Unicode.GetBytes(fullNameString);
        byte[] hash = SHA256.HashData(bytes);
        return
            BitConverter.ToUInt64(hash, 0) ^
            BitConverter.ToUInt64(hash, 8) ^
            BitConverter.ToUInt64(hash, 16) ^
            BitConverter.ToUInt64(hash, 24);
    }
}
